export type { Callto } from './callto'
export { callto } from './callto'
export { open } from './open'
export type { PhoneCall } from './phone-call'
export { phoneCall } from './phone-call'
export type { PhoneSms } from './phone-sms'
export { phoneSms } from './phone-sms'
export type { Tel } from './tel'
export { tel } from './tel'
