export * as cherryStudio from './cherry-studio'
export * as cursor from './cursor'
export * as githubDesktop from './github-desktop'
export * as idea from './idea'
export * as thunder from './thunder'
export * as vscode from './vscode'
export * as xcode from './xcode'
