import tailwindcss from '@tailwindcss/vite'
import { isUndefined } from 'lodash-es'
import { defineConfig } from 'vitepress'
import { groupIconMdPlugin, groupIconVitePlugin, localIconLoader } from 'vitepress-plugin-group-icons'
import llmstxt from 'vitepress-plugin-llms'
import pkg from '../../../packages/protocol-launcher/package.json' with { type: 'json' }

const isGithubPages = isUndefined(process.env.VERCEL)
const base = isGithubPages ? '/protocol-launcher/' : '/'

// https://vitepress.dev/reference/site-config
export default defineConfig({
  title: 'Protocol Launcher',
  description: 'One-click launch URL generator for protocol-based apps.',
  rewrites: {
    'en/:rest*': ':rest*',
    'en/index.md': 'index.md',
    'en/guide/what-is-it.md': 'guide/what-is-it.md',
    'en/guide/getting-started.md': 'guide/getting-started.md',
    'en/extra/examples.md': 'extra/examples.md',
    'en/apps/affine.md': 'apps/affine.md',
    'en/apps/agenda.md': 'apps/agenda.md',
    'en/apps/alfred.md': 'apps/alfred.md',
    'en/apps/antigravity.md': 'apps/antigravity.md',
    'en/apps/app-store.md': 'apps/app-store.md',
    'en/apps/appflowy.md': 'apps/appflowy.md',
    'en/apps/appigo-todo.md': 'apps/appigo-todo.md',
    'en/apps/apple-map.md': 'apps/apple-map.md',
    'en/apps/apple-script.md': 'apps/apple-script.md',
    'en/apps/atom.md': 'apps/atom.md',
    'en/apps/1writer.md': 'apps/1writer.md',
    'en/apps/bbedit.md': 'apps/bbedit.md',
    'en/apps/bear.md': 'apps/bear.md',
    'en/apps/cal2todo.md': 'apps/cal2todo.md',
    'en/apps/cherry-studio.md': 'apps/cherry-studio.md',
    'en/apps/code-buddy.md': 'apps/code-buddy.md',
    'en/apps/code-buddy-cn.md': 'apps/code-buddy-cn.md',
    'en/apps/codelite.md': 'apps/codelite.md',
    'en/apps/code-runner.md': 'apps/code-runner.md',
    'en/apps/codex.md': 'apps/codex.md',
    'en/apps/cursor.md': 'apps/cursor.md',
    'en/apps/2do.md': 'apps/2do.md',
    'en/apps/drafts.md': 'apps/drafts.md',
    'en/apps/editorial.md': 'apps/editorial.md',
    'en/apps/equipd-bible.md': 'apps/equipd-bible.md',
    'en/apps/due.md': 'apps/due.md',
    'en/apps/evernote.md': 'apps/evernote.md',
    'en/apps/fantastical.md': 'apps/fantastical.md',
    'en/apps/fsnotes.md': 'apps/fsnotes.md',
    'en/apps/github-desktop.md': 'apps/github-desktop.md',
    'en/apps/gladys.md': 'apps/gladys.md',
    'en/apps/goland.md': 'apps/goland.md',
    'en/apps/hbuilderx.md': 'apps/hbuilderx.md',
    'en/apps/hookmark.md': 'apps/hookmark.md',
    'en/apps/icab-mobile.md': 'apps/icab-mobile.md',
    'en/apps/idea.md': 'apps/idea.md',
    'en/apps/instapaper.md': 'apps/instapaper.md',
    'en/apps/interact.md': 'apps/interact.md',
    'en/apps/ipgmail.md': 'apps/ipgmail.md',
    'en/apps/itsycal.md': 'apps/itsycal.md',
    'en/apps/jump-desktop.md': 'apps/jump-desktop.md',
    'en/apps/kaleidoscope.md': 'apps/kaleidoscope.md',
    'en/apps/kiro.md': 'apps/kiro.md',
    'en/apps/lingma.md': 'apps/lingma.md',
    'en/apps/longshot.md': 'apps/longshot.md',
    'en/apps/macos.md': 'apps/macos.md',
    'en/apps/macvim.md': 'apps/macvim.md',
    'en/apps/mail-assistant.md': 'apps/mail-assistant.md',
    'en/apps/microsoft-edge.md': 'apps/microsoft-edge.md',
    'en/apps/motrix.md': 'apps/motrix.md',
    'en/apps/navicat.md': 'apps/navicat.md',
    'en/apps/nova.md': 'apps/nova.md',
    'en/apps/opencode.md': 'apps/opencode.md',
    'en/apps/orchids.md': 'apps/orchids.md',
    'en/apps/pearai.md': 'apps/pearai.md',
    'en/apps/pika.md': 'apps/pika.md',
    'en/apps/phpstorm.md': 'apps/phpstorm.md',
    'en/apps/pycharm.md': 'apps/pycharm.md',
    'en/apps/qoder.md': 'apps/qoder.md',
    'en/apps/quark.md': 'apps/quark.md',
    'en/apps/rustrover.md': 'apps/rustrover.md',
    'en/apps/shortcuts.md': 'apps/shortcuts.md',
    'en/apps/sketch.md': 'apps/sketch.md',
    'en/apps/soulver.md': 'apps/soulver.md',
    'en/apps/sourcetree.md': 'apps/sourcetree.md',
    'en/apps/steam.md': 'apps/steam.md',
    'en/apps/telegram.md': 'apps/telegram.md',
    'en/apps/termius.md': 'apps/termius.md',
    'en/apps/textmate.md': 'apps/textmate.md',
    'en/apps/theia.md': 'apps/theia.md',
    'en/apps/things.md': 'apps/things.md',
    'en/apps/thunder.md': 'apps/thunder.md',
    'en/apps/trae.md': 'apps/trae.md',
    'en/apps/trae-cn.md': 'apps/trae-cn.md',
    'en/apps/upic.md': 'apps/upic.md',
    'en/apps/verdent.md': 'apps/verdent.md',
    'en/apps/vscode.md': 'apps/vscode.md',
    'en/apps/vscode-insiders.md': 'apps/vscode-insiders.md',
    'en/apps/vscodium.md': 'apps/vscodium.md',
    'en/apps/webstorm.md': 'apps/webstorm.md',
    'en/apps/wemeet.md': 'apps/wemeet.md',
    'en/apps/windsurf.md': 'apps/windsurf.md',
    'en/apps/xcode.md': 'apps/xcode.md',
    'en/apps/zed.md': 'apps/zed.md',
  },
  base,
  head: [
    ['link', { rel: 'shortcut icon', href: `${base}logo.svg` }],
    ['link', { rel: 'apple-touch-icon', sizes: '180x180', href: `${base}logo.svg` }],
    ['meta', { name: 'baidu-site-verification', content: 'codeva-hoImtNdY4x' }],
  ],
  locales: {
    root: { label: 'English', lang: 'en-US', dir: 'ltr' },
    zh: { label: '简体中文', lang: 'zh-Hans', dir: 'ltr' },
  },
  themeConfig: {
    logo: '/logo.svg',
    socialLinks: [{ icon: 'github', link: 'https://github.com/zhensherlock/protocol-launcher' }],
    nav: [
      { text: 'Home', link: '/' },
      { text: 'Guide', link: '/guide/getting-started', activeMatch: '/guide/' },
      {
        text: pkg.version,
        items: [
          {
            text: 'Changelog',
            link: 'https://github.com/zhensherlock/protocol-launcher/blob/main/packages/protocol-launcher/CHANGELOG.md',
          },
        ],
      },
    ],

    outline: {
      level: [2, 6],
    },

    sidebar: [
      {
        text: 'Introduction',
        items: [
          { text: 'What is Protocol Launcher?', link: '/guide/what-is-it' },
          { text: 'Getting Started', link: '/guide/getting-started' },
        ],
      },
      {
        text: 'Applications',
        items: [
          { text: 'AFFiNE', link: '/apps/affine' },
          { text: 'Agenda', link: '/apps/agenda' },
          { text: 'Alfred', link: '/apps/alfred' },
          { text: 'Antigravity', link: '/apps/antigravity' },
          { text: 'App Store', link: '/apps/app-store' },
          { text: 'AppFlowy', link: '/apps/appflowy' },
          { text: 'Appigo Todo', link: '/apps/appigo-todo' },
          { text: 'Apple Map', link: '/apps/apple-map' },
          { text: 'Apple Script Editor', link: '/apps/apple-script' },
          { text: 'Atom', link: '/apps/atom' },
          { text: '1Writer', link: '/apps/1writer' },
          { text: 'BBEdit', link: '/apps/bbedit' },
          { text: 'Bear', link: '/apps/bear' },
          { text: 'Cal2Todo', link: '/apps/cal2todo' },
          { text: 'Cherry Studio', link: '/apps/cherry-studio' },
          { text: 'CodeBuddy', link: '/apps/code-buddy' },
          { text: 'CodeBuddy China', link: '/apps/code-buddy-cn' },
          { text: 'CodeLite', link: '/apps/codelite' },
          { text: 'CodeRunner', link: '/apps/code-runner' },
          { text: 'Codex', link: '/apps/codex' },
          { text: 'Cursor', link: '/apps/cursor' },
          { text: '2Do', link: '/apps/2do' },
          { text: 'Drafts', link: '/apps/drafts' },
          { text: 'Editorial', link: '/apps/editorial' },
          { text: 'Equipd Bible', link: '/apps/equipd-bible' },
          { text: 'Due', link: '/apps/due' },
          { text: 'Evernote', link: '/apps/evernote' },
          { text: 'Fantastical', link: '/apps/fantastical' },
          { text: 'FSNotes', link: '/apps/fsnotes' },
          { text: 'GitHub Desktop', link: '/apps/github-desktop' },
          { text: 'Gladys', link: '/apps/gladys' },
          { text: 'GoLand', link: '/apps/goland' },
          { text: 'HBuilderX', link: '/apps/hbuilderx' },
          { text: 'Hookmark', link: '/apps/hookmark' },
          { text: 'iCab Mobile', link: '/apps/icab-mobile' },
          { text: 'IntelliJ IDEA', link: '/apps/idea' },
          { text: 'Instapaper', link: '/apps/instapaper' },
          { text: 'Interact Scratchpad', link: '/apps/interact' },
          { text: 'iPGMail', link: '/apps/ipgmail' },
          { text: 'Itsycal', link: '/apps/itsycal' },
          { text: 'Jump Desktop', link: '/apps/jump-desktop' },
          { text: 'Kaleidoscope', link: '/apps/kaleidoscope' },
          { text: 'Kiro', link: '/apps/kiro' },
          { text: 'Lingma', link: '/apps/lingma' },
          { text: 'Longshot', link: '/apps/longshot' },
          { text: 'macOS', link: '/apps/macos' },
          { text: 'MacVim', link: '/apps/macvim' },
          { text: 'Mail Assistant', link: '/apps/mail-assistant' },
          { text: 'Microsoft Edge', link: '/apps/microsoft-edge' },
          { text: 'Motrix', link: '/apps/motrix' },
          { text: 'Navicat', link: '/apps/navicat' },
          { text: 'Nova', link: '/apps/nova' },
          { text: 'OpenCode', link: '/apps/opencode' },
          { text: 'Orchids', link: '/apps/orchids' },
          { text: 'PearAI', link: '/apps/pearai' },
          { text: 'Pika', link: '/apps/pika' },
          { text: 'PhpStorm', link: '/apps/phpstorm' },
          { text: 'PyCharm', link: '/apps/pycharm' },
          { text: 'Qoder', link: '/apps/qoder' },
          { text: 'Quark', link: '/apps/quark' },
          { text: 'RustRover', link: '/apps/rustrover' },
          { text: 'Shortcuts', link: '/apps/shortcuts' },
          { text: 'Sketch', link: '/apps/sketch' },
          { text: 'Soulver', link: '/apps/soulver' },
          { text: 'SourceTree', link: '/apps/sourcetree' },
          { text: 'Steam', link: '/apps/steam' },
          { text: 'Telegram', link: '/apps/telegram' },
          { text: 'Termius', link: '/apps/termius' },
          { text: 'TextMate', link: '/apps/textmate' },
          { text: 'Theia', link: '/apps/theia' },
          { text: 'Things', link: '/apps/things' },
          { text: 'Thunder', link: '/apps/thunder' },
          { text: 'Trae', link: '/apps/trae' },
          { text: 'Trae China', link: '/apps/trae-cn' },
          { text: 'uPic', link: '/apps/upic' },
          { text: 'Verdent', link: '/apps/verdent' },
          { text: 'VS Code', link: '/apps/vscode' },
          { text: 'VS Code Insiders', link: '/apps/vscode-insiders' },
          { text: 'VSCodium', link: '/apps/vscodium' },
          { text: 'WebStorm', link: '/apps/webstorm' },
          { text: 'WeMeet', link: '/apps/wemeet' },
          { text: 'Windsurf', link: '/apps/windsurf' },
          { text: 'Xcode', link: '/apps/xcode' },
          { text: 'Zed', link: '/apps/zed' },
        ],
      },
      {
        text: 'Extra',
        items: [{ text: 'Examples', link: '/extra/examples' }],
      },
    ],

    search: {
      provider: 'algolia',
      options: {
        appId: 'V6CF28P0PS',
        apiKey: '692752b7b3c6f794997d8ae22aed79fa',
        indexName: 'protocol-launcher',
        searchParameters: {
          facetFilters: [`tags:${isGithubPages ? 'gh' : 'vercel'}`],
        },
      },
    },
  },
  markdown: {
    config(md) {
      md.use(groupIconMdPlugin)
    },
  },
  vite: {
    server: {
      open: true,
    },
    plugins: [
      tailwindcss(),
      llmstxt({
        ignoreFiles: ['en/index.md', 'zh/index.md', 'CHANGELOG.md'],
        description:
          'TypeScript library for generating Quick Launch (deep link) URLs to trigger app actions with one click, e.g., installing plugins, configuring servers, or setting API keys.',
        sidebar: [
          {
            text: 'Introduction',
            base: '',
            items: [
              { text: 'What is Protocol Launcher?', link: '/guide/what-is-it' },
              { text: 'Getting Started', link: '/guide/getting-started' },
            ],
          },
          {
            text: 'Applications',
            base: '',
            items: [
              { text: 'AFFiNE', link: '/apps/affine' },
              { text: 'Agenda', link: '/apps/agenda' },
              { text: 'Alfred', link: '/apps/alfred' },
              { text: 'Antigravity', link: '/apps/antigravity' },
              { text: 'App Store', link: '/apps/app-store' },
              { text: 'AppFlowy', link: '/apps/appflowy' },
              { text: 'Appigo Todo', link: '/apps/appigo-todo' },
              { text: 'Apple Map', link: '/apps/apple-map' },
              { text: 'Apple Script Editor', link: '/apps/apple-script' },
              { text: 'Atom', link: '/apps/atom' },
              { text: '1Writer', link: '/apps/1writer' },
              { text: 'BBEdit', link: '/apps/bbedit' },
              { text: 'Bear', link: '/apps/bear' },
              { text: 'Cal2Todo', link: '/apps/cal2todo' },
              { text: 'Cherry Studio', link: '/apps/cherry-studio' },
              { text: 'CodeBuddy', link: '/apps/code-buddy' },
              { text: 'CodeBuddy China', link: '/apps/code-buddy-cn' },
              { text: 'CodeLite', link: '/apps/codelite' },
              { text: 'CodeRunner', link: '/apps/code-runner' },
              { text: 'Codex', link: '/apps/codex' },
              { text: 'Cursor', link: '/apps/cursor' },
              { text: '2Do', link: '/apps/2do' },
              { text: 'Drafts', link: '/apps/drafts' },
              { text: 'Editorial', link: '/apps/editorial' },
              { text: 'Equipd Bible', link: '/apps/equipd-bible' },
              { text: 'Due', link: '/apps/due' },
              { text: 'Evernote', link: '/apps/evernote' },
              { text: 'Fantastical', link: '/apps/fantastical' },
              { text: 'FSNotes', link: '/apps/fsnotes' },
              { text: 'GitHub Desktop', link: '/apps/github-desktop' },
              { text: 'Gladys', link: '/apps/gladys' },
              { text: 'GoLand', link: '/apps/goland' },
              { text: 'HBuilderX', link: '/apps/hbuilderx' },
              { text: 'Hookmark', link: '/apps/hookmark' },
              { text: 'iCab Mobile', link: '/apps/icab-mobile' },
              { text: 'IntelliJ IDEA', link: '/apps/idea' },
              { text: 'Instapaper', link: '/apps/instapaper' },
              { text: 'Interact Scratchpad', link: '/apps/interact' },
              { text: 'iPGMail', link: '/apps/ipgmail' },
              { text: 'Itsycal', link: '/apps/itsycal' },
              { text: 'Jump Desktop', link: '/apps/jump-desktop' },
              { text: 'Kaleidoscope', link: '/apps/kaleidoscope' },
              { text: 'Kiro', link: '/apps/kiro' },
              { text: 'Lingma', link: '/apps/lingma' },
              { text: 'Longshot', link: '/apps/longshot' },
              { text: 'macOS', link: '/apps/macos' },
              { text: 'MacVim', link: '/apps/macvim' },
              { text: 'Mail Assistant', link: '/apps/mail-assistant' },
              { text: 'Microsoft Edge', link: '/apps/microsoft-edge' },
              { text: 'Motrix', link: '/apps/motrix' },
              { text: 'Navicat', link: '/apps/navicat' },
              { text: 'Nova', link: '/apps/nova' },
              { text: 'OpenCode', link: '/apps/opencode' },
              { text: 'Orchids', link: '/apps/orchids' },
              { text: 'PearAI', link: '/apps/pearai' },
              { text: 'Pika', link: '/apps/pika' },
              { text: 'PhpStorm', link: '/apps/phpstorm' },
              { text: 'PyCharm', link: '/apps/pycharm' },
              { text: 'Qoder', link: '/apps/qoder' },
              { text: 'Quark', link: '/apps/quark' },
              { text: 'RustRover', link: '/apps/rustrover' },
              { text: 'Shortcuts', link: '/apps/shortcuts' },
              { text: 'Sketch', link: '/apps/sketch' },
              { text: 'Soulver', link: '/apps/soulver' },
              { text: 'SourceTree', link: '/apps/sourcetree' },
              { text: 'Steam', link: '/apps/steam' },
              { text: 'Telegram', link: '/apps/telegram' },
              { text: 'Termius', link: '/apps/termius' },
              { text: 'TextMate', link: '/apps/textmate' },
              { text: 'Theia', link: '/apps/theia' },
              { text: 'Things', link: '/apps/things' },
              { text: 'Thunder', link: '/apps/thunder' },
              { text: 'Trae', link: '/apps/trae' },
              { text: 'Trae China', link: '/apps/trae-cn' },
              { text: 'uPic', link: '/apps/upic' },
              { text: 'Verdent', link: '/apps/verdent' },
              { text: 'VS Code', link: '/apps/vscode' },
              { text: 'VS Code Insiders', link: '/apps/vscode-insiders' },
              { text: 'VSCodium', link: '/apps/vscodium' },
              { text: 'WebStorm', link: '/apps/webstorm' },
              { text: 'WeMeet', link: '/apps/wemeet' },
              { text: 'Windsurf', link: '/apps/windsurf' },
              { text: 'Xcode', link: '/apps/xcode' },
              { text: 'Zed', link: '/apps/zed' },
            ],
          },
          {
            text: '简介',
            base: '',
            items: [
              { text: '什么是 Protocol Launcher？', link: '/zh/guide/what-is-it' },
              { text: '快速开始', link: '/zh/guide/getting-started' },
            ],
          },
          {
            text: '应用程序',
            base: '',
            items: [
              { text: 'AFFiNE', link: '/zh/apps/affine' },
              { text: 'Alfred', link: '/zh/apps/alfred' },
              { text: 'Antigravity', link: '/zh/apps/antigravity' },
              { text: 'App Store', link: '/zh/apps/app-store' },
              { text: 'AppFlowy', link: '/zh/apps/appflowy' },
              { text: 'Apple Map', link: '/zh/apps/apple-map' },
              { text: 'Apple Script Editor', link: '/zh/apps/apple-script' },
              { text: 'Atom', link: '/zh/apps/atom' },
              { text: 'BBEdit', link: '/zh/apps/bbedit' },
              { text: 'Bear', link: '/zh/apps/bear' },
              { text: 'Cherry Studio', link: '/zh/apps/cherry-studio' },
              { text: 'CodeBuddy', link: '/zh/apps/code-buddy' },
              { text: 'CodeBuddy 中国版', link: '/zh/apps/code-buddy-cn' },
              { text: 'CodeLite', link: '/zh/apps/codelite' },
              { text: 'CodeRunner', link: '/zh/apps/code-runner' },
              { text: 'Codex', link: '/zh/apps/codex' },
              { text: 'Cursor', link: '/zh/apps/cursor' },
              { text: 'Evernote', link: '/zh/apps/evernote' },
              { text: 'Fantastical', link: '/zh/apps/fantastical' },
              { text: 'FSNotes', link: '/zh/apps/fsnotes' },
              { text: 'GitHub Desktop', link: '/zh/apps/github-desktop' },
              { text: 'GoLand', link: '/zh/apps/goland' },
              { text: 'HBuilderX', link: '/zh/apps/hbuilderx' },
              { text: 'IntelliJ IDEA', link: '/zh/apps/idea' },
              { text: 'Itsycal', link: '/zh/apps/itsycal' },
              { text: 'Jump Desktop', link: '/zh/apps/jump-desktop' },
              { text: 'Kaleidoscope', link: '/zh/apps/kaleidoscope' },
              { text: 'Kiro', link: '/zh/apps/kiro' },
              { text: 'Lingma', link: '/zh/apps/lingma' },
              { text: 'Longshot', link: '/zh/apps/longshot' },
              { text: 'macOS', link: '/zh/apps/macos' },
              { text: 'MacVim', link: '/zh/apps/macvim' },
              { text: 'Mail Assistant', link: '/zh/apps/mail-assistant' },
              { text: 'Microsoft Edge', link: '/zh/apps/microsoft-edge' },
              { text: 'Navicat', link: '/zh/apps/navicat' },
              { text: 'Nova', link: '/zh/apps/nova' },
              { text: 'OpenCode', link: '/zh/apps/opencode' },
              { text: 'Orchids', link: '/zh/apps/orchids' },
              { text: 'PearAI', link: '/zh/apps/pearai' },
              { text: 'Pika', link: '/zh/apps/pika' },
              { text: 'PhpStorm', link: '/zh/apps/phpstorm' },
              { text: 'PyCharm', link: '/zh/apps/pycharm' },
              { text: 'Qoder', link: '/zh/apps/qoder' },
              { text: 'Quark', link: '/zh/apps/quark' },
              { text: 'RustRover', link: '/zh/apps/rustrover' },
              { text: 'Shortcuts', link: '/zh/apps/shortcuts' },
              { text: 'Sketch', link: '/zh/apps/sketch' },
              { text: 'Soulver', link: '/zh/apps/soulver' },
              { text: 'SourceTree', link: '/zh/apps/sourcetree' },
              { text: 'Telegram', link: '/zh/apps/telegram' },
              { text: 'TextMate', link: '/zh/apps/textmate' },
              { text: 'Theia', link: '/zh/apps/theia' },
              { text: 'Things', link: '/zh/apps/things' },
              { text: 'Thunder', link: '/zh/apps/thunder' },
              { text: 'Trae', link: '/zh/apps/trae' },
              { text: 'Trae China', link: '/zh/apps/trae-cn' },
              { text: 'uPic', link: '/zh/apps/upic' },
              { text: 'Verdent', link: '/zh/apps/verdent' },
              { text: 'VS Code', link: '/zh/apps/vscode' },
              { text: 'VS Code Insiders', link: '/zh/apps/vscode-insiders' },
              { text: 'VSCodium', link: '/zh/apps/vscodium' },
              { text: 'WebStorm', link: '/zh/apps/webstorm' },
              { text: 'WeMeet', link: '/zh/apps/wemeet' },
              { text: 'Windsurf', link: '/zh/apps/windsurf' },
              { text: 'Xcode', link: '/zh/apps/xcode' },
              { text: 'Zed', link: '/zh/apps/zed' },
            ],
          },
          {
            text: '扩展',
            base: '',
            items: [{ text: '示例', link: '/zh/extra/examples' }],
          },
        ],
        details: `\
- 🛡️ Type-Safe
- 🧩 Multi-App Ready
- 🔬 On-Demand / Tree-shakable
- 🔐 Secure Encoding (safe configs, Unicode)
- ⚙️ Zero Runtime Dependencies
- 📦 ESM First
- 🚀 One-click deep links to trigger app actions
`,
      }),
      // https://icon-sets.iconify.design/logos/?keyword=logos
      // https://icon-sets.iconify.design/vscode-icons/?keyword=vscode-icons
      groupIconVitePlugin({
        customIcon: {
          'cherry studio': localIconLoader(import.meta.url, '../assets/cherry-studio.svg'),
          codebuddy: localIconLoader(import.meta.url, '../assets/codebuddy.svg'),
          cursor: localIconLoader(import.meta.url, '../assets/cursor.svg'),
          'github desktop': 'logos:github-octocat',
          goland: 'logos:goland',
          idea: 'logos:intellij-idea',
          phpstorm: 'logos:phpstorm',
          pycharm: 'logos:pycharm',
          rustrover: 'logos:rust',
          telegram: 'logos:telegram',
          thunder: localIconLoader(import.meta.url, '../assets/thunder.svg'),
          vscode: 'vscode-icons:file-type-vscode',
          webstorm: 'logos:webstorm',
          xcode: 'logos:xcode',
        },
      }),
    ],
  },
})
