import tailwindcss from '@tailwindcss/vite'
import { isUndefined } from 'lodash-es'
import { defineConfig } from 'vitepress'
import { groupIconMdPlugin, groupIconVitePlugin, localIconLoader } from 'vitepress-plugin-group-icons'
import llmstxt from 'vitepress-plugin-llms'
import pkg from '../../../packages/protocol-launcher/package.json' with { type: 'json' }

const isGithubPages = isUndefined(process.env.VERCEL)
const base = isGithubPages ? '/protocol-launcher/' : '/'

// https://vitepress.dev/reference/site-config
export default defineConfig({
  title: 'Protocol Launcher',
  description: 'One-click launch URL generator for protocol-based apps.',
  srcExclude: ['AGENTS.md', 'CLAUDE.md'],
  rewrites: {
    'en/:rest*': ':rest*',
    'en/index.md': 'index.md',
    'en/guide/what-is-it.md': 'guide/what-is-it.md',
    'en/guide/getting-started.md': 'guide/getting-started.md',
    'en/extra/examples.md': 'extra/examples.md',
    'en/apps/affine.md': 'apps/affine.md',
    'en/apps/agenda.md': 'apps/agenda.md',
    'en/apps/airmail.md': 'apps/airmail.md',
    'en/apps/alfred.md': 'apps/alfred.md',
    'en/apps/alter.md': 'apps/alter.md',
    'en/apps/antigravity.md': 'apps/antigravity.md',
    'en/apps/anybox.md': 'apps/anybox.md',
    'en/apps/anydesk.md': 'apps/anydesk.md',
    'en/apps/app-store.md': 'apps/app-store.md',
    'en/apps/appflowy.md': 'apps/appflowy.md',
    'en/apps/appigo-todo.md': 'apps/appigo-todo.md',
    'en/apps/apple-map.md': 'apps/apple-map.md',
    'en/apps/apple-script.md': 'apps/apple-script.md',
    'en/apps/arcgis-quickcapture.md': 'apps/arcgis-quickcapture.md',
    'en/apps/arcgis-survey123.md': 'apps/arcgis-survey123.md',
    'en/apps/atom.md': 'apps/atom.md',
    'en/apps/1writer.md': 'apps/1writer.md',
    'en/apps/barcuts.md': 'apps/barcuts.md',
    'en/apps/bbedit.md': 'apps/bbedit.md',
    'en/apps/bear.md': 'apps/bear.md',
    'en/apps/beorg.md': 'apps/beorg.md',
    'en/apps/bettertouchtool.md': 'apps/bettertouchtool.md',
    'en/apps/bike-outliner.md': 'apps/bike-outliner.md',
    'en/apps/box.md': 'apps/box.md',
    'en/apps/buchen.md': 'apps/buchen.md',
    'en/apps/bunch.md': 'apps/bunch.md',
    'en/apps/busycal.md': 'apps/busycal.md',
    'en/apps/busycontacts.md': 'apps/busycontacts.md',
    'en/apps/cal2todo.md': 'apps/cal2todo.md',
    'en/apps/calca.md': 'apps/calca.md',
    'en/apps/calendar-366.md': 'apps/calendar-366.md',
    'en/apps/calendars-readdle.md': 'apps/calendars-readdle.md',
    'en/apps/capacities.md': 'apps/capacities.md',
    'en/apps/cardhop.md': 'apps/cardhop.md',
    'en/apps/charty.md': 'apps/charty.md',
    'en/apps/cherry-studio.md': 'apps/cherry-studio.md',
    'en/apps/choosy.md': 'apps/choosy.md',
    'en/apps/chute.md': 'apps/chute.md',
    'en/apps/citymapper.md': 'apps/citymapper.md',
    'en/apps/cleanshot-x.md': 'apps/cleanshot-x.md',
    'en/apps/cloze.md': 'apps/cloze.md',
    'en/apps/coda.md': 'apps/coda.md',
    'en/apps/code-buddy.md': 'apps/code-buddy.md',
    'en/apps/code-buddy-cn.md': 'apps/code-buddy-cn.md',
    'en/apps/codelite.md': 'apps/codelite.md',
    'en/apps/code-runner.md': 'apps/code-runner.md',
    'en/apps/codehub.md': 'apps/codehub.md',
    'en/apps/codex.md': 'apps/codex.md',
    'en/apps/craft.md': 'apps/craft.md',
    'en/apps/cubox.md': 'apps/cubox.md',
    'en/apps/cursor.md': 'apps/cursor.md',
    'en/apps/dash.md': 'apps/dash.md',
    'en/apps/2do.md': 'apps/2do.md',
    'en/apps/day-one.md': 'apps/day-one.md',
    'en/apps/downcast.md': 'apps/downcast.md',
    'en/apps/debit-credit.md': 'apps/debit-credit.md',
    'en/apps/devonthink.md': 'apps/devonthink.md',
    'en/apps/diarly.md': 'apps/diarly.md',
    'en/apps/dict-cc.md': 'apps/dict-cc.md',
    'en/apps/drafts.md': 'apps/drafts.md',
    'en/apps/editorial.md': 'apps/editorial.md',
    'en/apps/equipd-bible.md': 'apps/equipd-bible.md',
    'en/apps/due.md': 'apps/due.md',
    'en/apps/dynamics-365-field-service-mobile.md': 'apps/dynamics-365-field-service-mobile.md',
    'en/apps/evernote.md': 'apps/evernote.md',
    'en/apps/fantastical.md': 'apps/fantastical.md',
    'en/apps/filemaker.md': 'apps/filemaker.md',
    'en/apps/find-any-file.md': 'apps/find-any-file.md',
    'en/apps/focus.md': 'apps/focus.md',
    'en/apps/foreflight-mobile.md': 'apps/foreflight-mobile.md',
    'en/apps/forscore.md': 'apps/forscore.md',
    'en/apps/fsnotes.md': 'apps/fsnotes.md',
    'en/apps/ftstreets.md': 'apps/ftstreets.md',
    'en/apps/fulcrum.md': 'apps/fulcrum.md',
    'en/apps/gett.md': 'apps/gett.md',
    'en/apps/github-desktop.md': 'apps/github-desktop.md',
    'en/apps/gladys.md': 'apps/gladys.md',
    'en/apps/goodlinks.md': 'apps/goodlinks.md',
    'en/apps/goodreader.md': 'apps/goodreader.md',
    'en/apps/goodtask.md': 'apps/goodtask.md',
    'en/apps/goland.md': 'apps/goland.md',
    'en/apps/google-chrome-ios.md': 'apps/google-chrome-ios.md',
    'en/apps/google-maps.md': 'apps/google-maps.md',
    'en/apps/guru-maps.md': 'apps/guru-maps.md',
    'en/apps/gv-connect.md': 'apps/gv-connect.md',
    'en/apps/hapigo.md': 'apps/hapigo.md',
    'en/apps/hbuilderx.md': 'apps/hbuilderx.md',
    'en/apps/hammerspoon.md': 'apps/hammerspoon.md',
    'en/apps/hiddify.md': 'apps/hiddify.md',
    'en/apps/highlights.md': 'apps/highlights.md',
    'en/apps/home-assistant.md': 'apps/home-assistant.md',
    'en/apps/hookmark.md': 'apps/hookmark.md',
    'en/apps/hot-tub.md': 'apps/hot-tub.md',
    'en/apps/houdahspot.md': 'apps/houdahspot.md',
    'en/apps/ia-writer.md': 'apps/ia-writer.md',
    'en/apps/icab-mobile.md': 'apps/icab-mobile.md',
    'en/apps/idea.md': 'apps/idea.md',
    'en/apps/infuse.md': 'apps/infuse.md',
    'en/apps/inroute.md': 'apps/inroute.md',
    'en/apps/instapaper.md': 'apps/instapaper.md',
    'en/apps/interact.md': 'apps/interact.md',
    'en/apps/ipgmail.md': 'apps/ipgmail.md',
    'en/apps/ireal-pro.md': 'apps/ireal-pro.md',
    'en/apps/ithoughts.md': 'apps/ithoughts.md',
    'en/apps/itsycal.md': 'apps/itsycal.md',
    'en/apps/ivanti-web-work.md': 'apps/ivanti-web-work.md',
    'en/apps/ivory.md': 'apps/ivory.md',
    'en/apps/joplin.md': 'apps/joplin.md',
    'en/apps/jump-desktop.md': 'apps/jump-desktop.md',
    'en/apps/just-timers.md': 'apps/just-timers.md',
    'en/apps/kakao-map.md': 'apps/kakao-map.md',
    'en/apps/keyboard-maestro.md': 'apps/keyboard-maestro.md',
    'en/apps/kaleidoscope.md': 'apps/kaleidoscope.md',
    'en/apps/keepit.md': 'apps/keepit.md',
    'en/apps/kiro.md': 'apps/kiro.md',
    'en/apps/launch-center-pro.md': 'apps/launch-center-pro.md',
    'en/apps/launchbar.md': 'apps/launchbar.md',
    'en/apps/letterboxd.md': 'apps/letterboxd.md',
    'en/apps/line.md': 'apps/line.md',
    'en/apps/lingma.md': 'apps/lingma.md',
    'en/apps/locus-map.md': 'apps/locus-map.md',
    'en/apps/longshot.md': 'apps/longshot.md',
    'en/apps/macos.md': 'apps/macos.md',
    'en/apps/macvim.md': 'apps/macvim.md',
    'en/apps/mail-assistant.md': 'apps/mail-assistant.md',
    'en/apps/marked.md': 'apps/marked.md',
    'en/apps/mattermost.md': 'apps/mattermost.md',
    'en/apps/mical.md': 'apps/mical.md',
    'en/apps/microsoft-edge.md': 'apps/microsoft-edge.md',
    'en/apps/microsoft-office.md': 'apps/microsoft-office.md',
    'en/apps/microsoft-onenote.md': 'apps/microsoft-onenote.md',
    'en/apps/microsoft-remote-desktop.md': 'apps/microsoft-remote-desktop.md',
    'en/apps/microsoft-teams.md': 'apps/microsoft-teams.md',
    'en/apps/mindnode.md': 'apps/mindnode.md',
    'en/apps/momento.md': 'apps/momento.md',
    'en/apps/moneywiz.md': 'apps/moneywiz.md',
    'en/apps/moovit.md': 'apps/moovit.md',
    'en/apps/motrix.md': 'apps/motrix.md',
    'en/apps/multi-timer.md': 'apps/multi-timer.md',
    'en/apps/naver-map.md': 'apps/naver-map.md',
    'en/apps/navicat.md': 'apps/navicat.md',
    'en/apps/noteplan.md': 'apps/noteplan.md',
    'en/apps/notebooks.md': 'apps/notebooks.md',
    'en/apps/nozbe.md': 'apps/nozbe.md',
    'en/apps/nova.md': 'apps/nova.md',
    'en/apps/obsidian.md': 'apps/obsidian.md',
    'en/apps/ok-json.md': 'apps/ok-json.md',
    'en/apps/omnifocus.md': 'apps/omnifocus.md',
    'en/apps/omnioutliner.md': 'apps/omnioutliner.md',
    'en/apps/onsong.md': 'apps/onsong.md',
    'en/apps/opencode.md': 'apps/opencode.md',
    'en/apps/opener.md': 'apps/opener.md',
    'en/apps/openvpn-connect.md': 'apps/openvpn-connect.md',
    'en/apps/orchids.md': 'apps/orchids.md',
    'en/apps/organic-maps.md': 'apps/organic-maps.md',
    'en/apps/orion-browser.md': 'apps/orion-browser.md',
    'en/apps/overcast.md': 'apps/overcast.md',
    'en/apps/panorama-x.md': 'apps/panorama-x.md',
    'en/apps/pcalc.md': 'apps/pcalc.md',
    'en/apps/pearai.md': 'apps/pearai.md',
    'en/apps/pdf-expert.md': 'apps/pdf-expert.md',
    'en/apps/pdf-viewer.md': 'apps/pdf-viewer.md',
    'en/apps/permute.md': 'apps/permute.md',
    'en/apps/pika.md': 'apps/pika.md',
    'en/apps/picsew.md': 'apps/picsew.md',
    'en/apps/pincase.md': 'apps/pincase.md',
    'en/apps/pleco.md': 'apps/pleco.md',
    'en/apps/pocket-casts.md': 'apps/pocket-casts.md',
    'en/apps/power-apps-mobile.md': 'apps/power-apps-mobile.md',
    'en/apps/power-bi-mobile.md': 'apps/power-bi-mobile.md',
    'en/apps/postman.md': 'apps/postman.md',
    'en/apps/prizmo.md': 'apps/prizmo.md',
    'en/apps/pushcut.md': 'apps/pushcut.md',
    'en/apps/phpstorm.md': 'apps/phpstorm.md',
    'en/apps/pycharm.md': 'apps/pycharm.md',
    'en/apps/pythonista.md': 'apps/pythonista.md',
    'en/apps/pyto.md': 'apps/pyto.md',
    'en/apps/qoder.md': 'apps/qoder.md',
    'en/apps/quark.md': 'apps/quark.md',
    'en/apps/raycast.md': 'apps/raycast.md',
    'en/apps/remote-desktop-manager.md': 'apps/remote-desktop-manager.md',
    'en/apps/reeder.md': 'apps/reeder.md',
    'en/apps/ringcentral.md': 'apps/ringcentral.md',
    'en/apps/royal-ts.md': 'apps/royal-ts.md',
    'en/apps/rustrover.md': 'apps/rustrover.md',
    'en/apps/salesforce-mobile.md': 'apps/salesforce-mobile.md',
    'en/apps/scannr.md': 'apps/scannr.md',
    'en/apps/screens.md': 'apps/screens.md',
    'en/apps/scriptable.md': 'apps/scriptable.md',
    'en/apps/shopi.md': 'apps/shopi.md',
    'en/apps/shortcuts.md': 'apps/shortcuts.md',
    'en/apps/simple-scan.md': 'apps/simple-scan.md',
    'en/apps/sketch.md': 'apps/sketch.md',
    'en/apps/skype.md': 'apps/skype.md',
    'en/apps/slack.md': 'apps/slack.md',
    'en/apps/soulver.md': 'apps/soulver.md',
    'en/apps/sorted.md': 'apps/sorted.md',
    'en/apps/sourcetree.md': 'apps/sourcetree.md',
    'en/apps/spark.md': 'apps/spark.md',
    'en/apps/splashtop-business.md': 'apps/splashtop-business.md',
    'en/apps/spotify.md': 'apps/spotify.md',
    'en/apps/steam.md': 'apps/steam.md',
    'en/apps/stream-deck.md': 'apps/stream-deck.md',
    'en/apps/story-planner.md': 'apps/story-planner.md',
    'en/apps/surge.md': 'apps/surge.md',
    'en/apps/tablepro.md': 'apps/tablepro.md',
    'en/apps/tadam.md': 'apps/tadam.md',
    'en/apps/tally.md': 'apps/tally.md',
    'en/apps/telegram.md': 'apps/telegram.md',
    'en/apps/tembo.md': 'apps/tembo.md',
    'en/apps/terminology.md': 'apps/terminology.md',
    'en/apps/termius.md': 'apps/termius.md',
    'en/apps/textastic.md': 'apps/textastic.md',
    'en/apps/textwell.md': 'apps/textwell.md',
    'en/apps/textmate.md': 'apps/textmate.md',
    'en/apps/theia.md': 'apps/theia.md',
    'en/apps/things.md': 'apps/things.md',
    'en/apps/thunder.md': 'apps/thunder.md',
    'en/apps/tim.md': 'apps/tim.md',
    'en/apps/timing.md': 'apps/timing.md',
    'en/apps/timer-plus.md': 'apps/timer-plus.md',
    'en/apps/timepage.md': 'apps/timepage.md',
    'en/apps/today-habit-tracker.md': 'apps/today-habit-tracker.md',
    'en/apps/todoist.md': 'apps/todoist.md',
    'en/apps/tower.md': 'apps/tower.md',
    'en/apps/trae.md': 'apps/trae.md',
    'en/apps/trae-cn.md': 'apps/trae-cn.md',
    'en/apps/trello.md': 'apps/trello.md',
    'en/apps/truecontext.md': 'apps/truecontext.md',
    'en/apps/ulysses.md': 'apps/ulysses.md',
    'en/apps/upic.md': 'apps/upic.md',
    'en/apps/upnote.md': 'apps/upnote.md',
    'en/apps/verdent.md': 'apps/verdent.md',
    'en/apps/viber.md': 'apps/viber.md',
    'en/apps/vscode.md': 'apps/vscode.md',
    'en/apps/vscode-insiders.md': 'apps/vscode-insiders.md',
    'en/apps/vscodium.md': 'apps/vscodium.md',
    'en/apps/warp.md': 'apps/warp.md',
    'en/apps/waterminder.md': 'apps/waterminder.md',
    'en/apps/waze.md': 'apps/waze.md',
    'en/apps/webex.md': 'apps/webex.md',
    'en/apps/webstorm.md': 'apps/webstorm.md',
    'en/apps/wemeet.md': 'apps/wemeet.md',
    'en/apps/what3words.md': 'apps/what3words.md',
    'en/apps/whereto.md': 'apps/whereto.md',
    'en/apps/windsurf.md': 'apps/windsurf.md',
    'en/apps/working-copy.md': 'apps/working-copy.md',
    'en/apps/written-down.md': 'apps/written-down.md',
    'en/apps/xcode.md': 'apps/xcode.md',
    'en/apps/yandex-maps.md': 'apps/yandex-maps.md',
    'en/apps/yandex-navigator.md': 'apps/yandex-navigator.md',
    'en/apps/yoink-ios.md': 'apps/yoink-ios.md',
    'en/apps/zed.md': 'apps/zed.md',
    'en/apps/zoom.md': 'apps/zoom.md',
  },
  base,
  head: [
    ['link', { rel: 'shortcut icon', href: `${base}logo.svg` }],
    ['link', { rel: 'apple-touch-icon', sizes: '180x180', href: `${base}logo.svg` }],
    ['meta', { name: 'baidu-site-verification', content: 'codeva-hoImtNdY4x' }],
  ],
  locales: {
    root: { label: 'English', lang: 'en-US', dir: 'ltr' },
    zh: { label: '简体中文', lang: 'zh-Hans', dir: 'ltr' },
  },
  themeConfig: {
    logo: '/logo.svg',
    socialLinks: [{ icon: 'github', link: 'https://github.com/zhensherlock/protocol-launcher' }],
    nav: [
      { text: 'Home', link: '/' },
      { text: 'Guide', link: '/guide/getting-started', activeMatch: '/guide/' },
      {
        text: pkg.version,
        items: [
          {
            text: 'Changelog',
            link: 'https://github.com/zhensherlock/protocol-launcher/blob/main/packages/protocol-launcher/CHANGELOG.md',
          },
        ],
      },
    ],

    outline: {
      level: [2, 6],
    },

    sidebar: [
      {
        text: 'Introduction',
        items: [
          { text: 'What is Protocol Launcher?', link: '/guide/what-is-it' },
          { text: 'Getting Started', link: '/guide/getting-started' },
        ],
      },
      {
        text: 'Applications',
        items: [
          { text: 'AFFiNE', link: '/apps/affine' },
          { text: 'Agenda', link: '/apps/agenda' },
          { text: 'Airmail', link: '/apps/airmail' },
          { text: 'Alfred', link: '/apps/alfred' },
          { text: 'Alter', link: '/apps/alter' },
          { text: 'Antigravity', link: '/apps/antigravity' },
          { text: 'Anybox', link: '/apps/anybox' },
          { text: 'AnyDesk', link: '/apps/anydesk' },
          { text: 'App Store', link: '/apps/app-store' },
          { text: 'AppFlowy', link: '/apps/appflowy' },
          { text: 'Appigo Todo', link: '/apps/appigo-todo' },
          { text: 'Apple Maps', link: '/apps/apple-map' },
          { text: 'Apple Script Editor', link: '/apps/apple-script' },
          { text: 'ArcGIS QuickCapture', link: '/apps/arcgis-quickcapture' },
          { text: 'ArcGIS Survey123', link: '/apps/arcgis-survey123' },
          { text: 'Atom', link: '/apps/atom' },
          { text: '1Writer', link: '/apps/1writer' },
          { text: 'BarCuts', link: '/apps/barcuts' },
          { text: 'BBEdit', link: '/apps/bbedit' },
          { text: 'Bear', link: '/apps/bear' },
          { text: 'Beorg', link: '/apps/beorg' },
          { text: 'BetterTouchTool', link: '/apps/bettertouchtool' },
          { text: 'Bike Outliner', link: '/apps/bike-outliner' },
          { text: 'Box', link: '/apps/box' },
          { text: 'Buchen', link: '/apps/buchen' },
          { text: 'Bunch', link: '/apps/bunch' },
          { text: 'BusyCal', link: '/apps/busycal' },
          { text: 'BusyContacts', link: '/apps/busycontacts' },
          { text: 'Cal2Todo', link: '/apps/cal2todo' },
          { text: 'Calca', link: '/apps/calca' },
          { text: 'Calendar 366', link: '/apps/calendar-366' },
          { text: 'Calendars by Readdle', link: '/apps/calendars-readdle' },
          { text: 'Capacities', link: '/apps/capacities' },
          { text: 'Cardhop', link: '/apps/cardhop' },
          { text: 'Charty', link: '/apps/charty' },
          { text: 'Cherry Studio', link: '/apps/cherry-studio' },
          { text: 'Choosy', link: '/apps/choosy' },
          { text: 'Chute', link: '/apps/chute' },
          { text: 'Citymapper', link: '/apps/citymapper' },
          { text: 'CleanShot X', link: '/apps/cleanshot-x' },
          { text: 'Cloze', link: '/apps/cloze' },
          { text: 'Coda', link: '/apps/coda' },
          { text: 'CodeBuddy', link: '/apps/code-buddy' },
          { text: 'CodeBuddy China', link: '/apps/code-buddy-cn' },
          { text: 'CodeLite', link: '/apps/codelite' },
          { text: 'CodeRunner', link: '/apps/code-runner' },
          { text: 'CodeHub', link: '/apps/codehub' },
          { text: 'Codex', link: '/apps/codex' },
          { text: 'Craft', link: '/apps/craft' },
          { text: 'Cubox', link: '/apps/cubox' },
          { text: 'Cursor', link: '/apps/cursor' },
          { text: 'Dash', link: '/apps/dash' },
          { text: '2Do', link: '/apps/2do' },
          { text: 'Day One', link: '/apps/day-one' },
          { text: 'Downcast', link: '/apps/downcast' },
          { text: 'Debit & Credit', link: '/apps/debit-credit' },
          { text: 'DEVONthink', link: '/apps/devonthink' },
          { text: 'Diarly', link: '/apps/diarly' },
          { text: 'dict.cc', link: '/apps/dict-cc' },
          { text: 'Drafts', link: '/apps/drafts' },
          { text: 'Editorial', link: '/apps/editorial' },
          { text: 'Equipd Bible', link: '/apps/equipd-bible' },
          { text: 'Due', link: '/apps/due' },
          { text: 'Dynamics 365 Field Service Mobile', link: '/apps/dynamics-365-field-service-mobile' },
          { text: 'Evernote', link: '/apps/evernote' },
          { text: 'Fantastical', link: '/apps/fantastical' },
          { text: 'Claris FileMaker', link: '/apps/filemaker' },
          { text: 'Find Any File', link: '/apps/find-any-file' },
          { text: 'Focus', link: '/apps/focus' },
          { text: 'ForeFlight Mobile', link: '/apps/foreflight-mobile' },
          { text: 'forScore', link: '/apps/forscore' },
          { text: 'FSNotes', link: '/apps/fsnotes' },
          { text: 'Streets', link: '/apps/ftstreets' },
          { text: 'Fulcrum', link: '/apps/fulcrum' },
          { text: 'Gett', link: '/apps/gett' },
          { text: 'GitHub Desktop', link: '/apps/github-desktop' },
          { text: 'Gladys', link: '/apps/gladys' },
          { text: 'GoodLinks', link: '/apps/goodlinks' },
          { text: 'GoodReader', link: '/apps/goodreader' },
          { text: 'GoodTask', link: '/apps/goodtask' },
          { text: 'GoLand', link: '/apps/goland' },
          { text: 'Google Chrome iOS', link: '/apps/google-chrome-ios' },
          { text: 'Google Maps', link: '/apps/google-maps' },
          { text: 'Guru Maps', link: '/apps/guru-maps' },
          { text: 'GV Connect', link: '/apps/gv-connect' },
          { text: 'HapiGo', link: '/apps/hapigo' },
          { text: 'HBuilderX', link: '/apps/hbuilderx' },
          { text: 'Hammerspoon', link: '/apps/hammerspoon' },
          { text: 'Hiddify', link: '/apps/hiddify' },
          { text: 'Highlights', link: '/apps/highlights' },
          { text: 'Home Assistant', link: '/apps/home-assistant' },
          { text: 'Hookmark', link: '/apps/hookmark' },
          { text: 'Hot Tub', link: '/apps/hot-tub' },
          { text: 'HoudahSpot', link: '/apps/houdahspot' },
          { text: 'iA Writer', link: '/apps/ia-writer' },
          { text: 'iCab Mobile', link: '/apps/icab-mobile' },
          { text: 'IntelliJ IDEA', link: '/apps/idea' },
          { text: 'Infuse', link: '/apps/infuse' },
          { text: 'inRoute', link: '/apps/inroute' },
          { text: 'Instapaper', link: '/apps/instapaper' },
          { text: 'Interact Scratchpad', link: '/apps/interact' },
          { text: 'iPGMail', link: '/apps/ipgmail' },
          { text: 'iReal Pro', link: '/apps/ireal-pro' },
          { text: 'iThoughts', link: '/apps/ithoughts' },
          { text: 'Itsycal', link: '/apps/itsycal' },
          { text: 'Ivanti Web@Work', link: '/apps/ivanti-web-work' },
          { text: 'Ivory', link: '/apps/ivory' },
          { text: 'Joplin', link: '/apps/joplin' },
          { text: 'Jump Desktop', link: '/apps/jump-desktop' },
          { text: 'Just Timers', link: '/apps/just-timers' },
          { text: 'Kakao Map', link: '/apps/kakao-map' },
          { text: 'Keyboard Maestro', link: '/apps/keyboard-maestro' },
          { text: 'Kaleidoscope', link: '/apps/kaleidoscope' },
          { text: 'Keep It', link: '/apps/keepit' },
          { text: 'Kiro', link: '/apps/kiro' },
          { text: 'Launch Center Pro', link: '/apps/launch-center-pro' },
          { text: 'LaunchBar', link: '/apps/launchbar' },
          { text: 'Letterboxd', link: '/apps/letterboxd' },
          { text: 'LINE', link: '/apps/line' },
          { text: 'Lingma', link: '/apps/lingma' },
          { text: 'Locus Map', link: '/apps/locus-map' },
          { text: 'Longshot', link: '/apps/longshot' },
          { text: 'macOS', link: '/apps/macos' },
          { text: 'MacVim', link: '/apps/macvim' },
          { text: 'Mail Assistant', link: '/apps/mail-assistant' },
          { text: 'Marked', link: '/apps/marked' },
          { text: 'Mattermost', link: '/apps/mattermost' },
          { text: 'miCal', link: '/apps/mical' },
          { text: 'Microsoft Edge', link: '/apps/microsoft-edge' },
          { text: 'Microsoft Office', link: '/apps/microsoft-office' },
          { text: 'Microsoft OneNote', link: '/apps/microsoft-onenote' },
          { text: 'Microsoft Remote Desktop', link: '/apps/microsoft-remote-desktop' },
          { text: 'Microsoft Teams', link: '/apps/microsoft-teams' },
          { text: 'MindNode', link: '/apps/mindnode' },
          { text: 'Momento', link: '/apps/momento' },
          { text: 'MoneyWiz', link: '/apps/moneywiz' },
          { text: 'Moovit', link: '/apps/moovit' },
          { text: 'Motrix', link: '/apps/motrix' },
          { text: 'MultiTimer', link: '/apps/multi-timer' },
          { text: 'NAVER Map', link: '/apps/naver-map' },
          { text: 'Navicat', link: '/apps/navicat' },
          { text: 'NotePlan', link: '/apps/noteplan' },
          { text: 'Notebooks', link: '/apps/notebooks' },
          { text: 'Nozbe', link: '/apps/nozbe' },
          { text: 'Nova', link: '/apps/nova' },
          { text: 'Obsidian', link: '/apps/obsidian' },
          { text: 'OK JSON', link: '/apps/ok-json' },
          { text: 'OmniFocus', link: '/apps/omnifocus' },
          { text: 'OmniOutliner', link: '/apps/omnioutliner' },
          { text: 'OnSong', link: '/apps/onsong' },
          { text: 'OpenCode', link: '/apps/opencode' },
          { text: 'Opener', link: '/apps/opener' },
          { text: 'OpenVPN Connect', link: '/apps/openvpn-connect' },
          { text: 'Orchids', link: '/apps/orchids' },
          { text: 'Organic Maps', link: '/apps/organic-maps' },
          { text: 'Orion Browser', link: '/apps/orion-browser' },
          { text: 'Overcast', link: '/apps/overcast' },
          { text: 'Panorama X', link: '/apps/panorama-x' },
          { text: 'PCalc', link: '/apps/pcalc' },
          { text: 'PearAI', link: '/apps/pearai' },
          { text: 'PDF Expert', link: '/apps/pdf-expert' },
          { text: 'PDF Viewer', link: '/apps/pdf-viewer' },
          { text: 'Permute', link: '/apps/permute' },
          { text: 'Pika', link: '/apps/pika' },
          { text: 'Picsew', link: '/apps/picsew' },
          { text: 'Pincase', link: '/apps/pincase' },
          { text: 'Pleco', link: '/apps/pleco' },
          { text: 'Pocket Casts', link: '/apps/pocket-casts' },
          { text: 'Power Apps Mobile', link: '/apps/power-apps-mobile' },
          { text: 'Power BI Mobile', link: '/apps/power-bi-mobile' },
          { text: 'Postman', link: '/apps/postman' },
          { text: 'Prizmo', link: '/apps/prizmo' },
          { text: 'Pushcut', link: '/apps/pushcut' },
          { text: 'PhpStorm', link: '/apps/phpstorm' },
          { text: 'PyCharm', link: '/apps/pycharm' },
          { text: 'Pythonista', link: '/apps/pythonista' },
          { text: 'Pyto', link: '/apps/pyto' },
          { text: 'Qoder', link: '/apps/qoder' },
          { text: 'Quark', link: '/apps/quark' },
          { text: 'Raycast', link: '/apps/raycast' },
          { text: 'Remote Desktop Manager', link: '/apps/remote-desktop-manager' },
          { text: 'Reeder', link: '/apps/reeder' },
          { text: 'RingCentral', link: '/apps/ringcentral' },
          { text: 'Royal TS', link: '/apps/royal-ts' },
          { text: 'RustRover', link: '/apps/rustrover' },
          { text: 'Salesforce Mobile', link: '/apps/salesforce-mobile' },
          { text: 'Scannr', link: '/apps/scannr' },
          { text: 'Screens', link: '/apps/screens' },
          { text: 'Scriptable', link: '/apps/scriptable' },
          { text: 'Shopi', link: '/apps/shopi' },
          { text: 'Shortcuts', link: '/apps/shortcuts' },
          { text: 'Simple Scan', link: '/apps/simple-scan' },
          { text: 'Sketch', link: '/apps/sketch' },
          { text: 'Skype', link: '/apps/skype' },
          { text: 'Slack', link: '/apps/slack' },
          { text: 'Soulver', link: '/apps/soulver' },
          { text: 'Sorted³', link: '/apps/sorted' },
          { text: 'SourceTree', link: '/apps/sourcetree' },
          { text: 'Spark Mail', link: '/apps/spark' },
          { text: 'Splashtop Business', link: '/apps/splashtop-business' },
          { text: 'Spotify', link: '/apps/spotify' },
          { text: 'Steam', link: '/apps/steam' },
          { text: 'Stream Deck', link: '/apps/stream-deck' },
          { text: 'Story Planner', link: '/apps/story-planner' },
          { text: 'Surge', link: '/apps/surge' },
          { text: 'TablePro', link: '/apps/tablepro' },
          { text: 'Tadam', link: '/apps/tadam' },
          { text: 'Tally', link: '/apps/tally' },
          { text: 'Telegram', link: '/apps/telegram' },
          { text: 'Tembo', link: '/apps/tembo' },
          { text: 'Terminology', link: '/apps/terminology' },
          { text: 'Termius', link: '/apps/termius' },
          { text: 'Textastic', link: '/apps/textastic' },
          { text: 'Textwell', link: '/apps/textwell' },
          { text: 'TextMate', link: '/apps/textmate' },
          { text: 'Theia', link: '/apps/theia' },
          { text: 'Things', link: '/apps/things' },
          { text: 'Thunder', link: '/apps/thunder' },
          { text: 'Tim', link: '/apps/tim' },
          { text: 'Timing', link: '/apps/timing' },
          { text: 'Timer+', link: '/apps/timer-plus' },
          { text: 'Timepage', link: '/apps/timepage' },
          { text: 'Today Habit Tracker', link: '/apps/today-habit-tracker' },
          { text: 'Todoist', link: '/apps/todoist' },
          { text: 'Tower', link: '/apps/tower' },
          { text: 'Trae', link: '/apps/trae' },
          { text: 'Trae China', link: '/apps/trae-cn' },
          { text: 'Trello', link: '/apps/trello' },
          { text: 'TrueContext', link: '/apps/truecontext' },
          { text: 'Ulysses', link: '/apps/ulysses' },
          { text: 'uPic', link: '/apps/upic' },
          { text: 'UpNote', link: '/apps/upnote' },
          { text: 'Verdent', link: '/apps/verdent' },
          { text: 'Viber', link: '/apps/viber' },
          { text: 'VS Code', link: '/apps/vscode' },
          { text: 'VS Code Insiders', link: '/apps/vscode-insiders' },
          { text: 'VSCodium', link: '/apps/vscodium' },
          { text: 'Warp', link: '/apps/warp' },
          { text: 'WaterMinder', link: '/apps/waterminder' },
          { text: 'Waze', link: '/apps/waze' },
          { text: 'Webex', link: '/apps/webex' },
          { text: 'WebStorm', link: '/apps/webstorm' },
          { text: 'WeMeet', link: '/apps/wemeet' },
          { text: 'what3words', link: '/apps/what3words' },
          { text: 'Where To', link: '/apps/whereto' },
          { text: 'Windsurf', link: '/apps/windsurf' },
          { text: 'Working Copy', link: '/apps/working-copy' },
          { text: 'Written Down', link: '/apps/written-down' },
          { text: 'Xcode', link: '/apps/xcode' },
          { text: 'Yandex Maps', link: '/apps/yandex-maps' },
          { text: 'Yandex Navigator', link: '/apps/yandex-navigator' },
          { text: 'Yoink for iOS', link: '/apps/yoink-ios' },
          { text: 'Zed', link: '/apps/zed' },
          { text: 'Zoom', link: '/apps/zoom' },
        ],
      },
      {
        text: 'Extra',
        items: [{ text: 'Examples', link: '/extra/examples' }],
      },
    ],

    search: {
      provider: 'local',
      // provider: 'algolia',
      // options: {
      //   appId: 'V6CF28P0PS',
      //   apiKey: '692752b7b3c6f794997d8ae22aed79fa',
      //   indexName: 'protocol-launcher',
      //   searchParameters: {
      //     facetFilters: [`tags:${isGithubPages ? 'gh' : 'vercel'}`],
      //   },
      // },
    },
  },
  markdown: {
    config(md) {
      md.use(groupIconMdPlugin)
    },
  },
  vite: {
    server: {
      open: true,
    },
    plugins: [
      tailwindcss(),
      llmstxt({
        ignoreFiles: ['en/index.md', 'zh/index.md', 'CHANGELOG.md', 'AGENTS.md', 'CLAUDE.md'],
        description:
          'TypeScript library for generating Quick Launch (deep link) URLs to trigger app actions with one click, e.g., installing plugins, configuring servers, or setting API keys.',
        sidebar: [
          {
            text: 'Introduction',
            base: '',
            items: [
              { text: 'What is Protocol Launcher?', link: '/guide/what-is-it' },
              { text: 'Getting Started', link: '/guide/getting-started' },
            ],
          },
          {
            text: 'Applications',
            base: '',
            items: [
              { text: 'AFFiNE', link: '/apps/affine' },
              { text: 'Agenda', link: '/apps/agenda' },
              { text: 'Airmail', link: '/apps/airmail' },
              { text: 'Alfred', link: '/apps/alfred' },
              { text: 'Alter', link: '/apps/alter' },
              { text: 'Antigravity', link: '/apps/antigravity' },
              { text: 'Anybox', link: '/apps/anybox' },
              { text: 'AnyDesk', link: '/apps/anydesk' },
              { text: 'App Store', link: '/apps/app-store' },
              { text: 'AppFlowy', link: '/apps/appflowy' },
              { text: 'Appigo Todo', link: '/apps/appigo-todo' },
              { text: 'Apple Maps', link: '/apps/apple-map' },
              { text: 'Apple Script Editor', link: '/apps/apple-script' },
              { text: 'ArcGIS QuickCapture', link: '/apps/arcgis-quickcapture' },
              { text: 'ArcGIS Survey123', link: '/apps/arcgis-survey123' },
              { text: 'Atom', link: '/apps/atom' },
              { text: '1Writer', link: '/apps/1writer' },
              { text: 'BarCuts', link: '/apps/barcuts' },
              { text: 'BBEdit', link: '/apps/bbedit' },
              { text: 'Bear', link: '/apps/bear' },
              { text: 'Beorg', link: '/apps/beorg' },
              { text: 'BetterTouchTool', link: '/apps/bettertouchtool' },
              { text: 'Bike Outliner', link: '/apps/bike-outliner' },
              { text: 'Box', link: '/apps/box' },
              { text: 'Buchen', link: '/apps/buchen' },
              { text: 'Bunch', link: '/apps/bunch' },
              { text: 'BusyCal', link: '/apps/busycal' },
              { text: 'BusyContacts', link: '/apps/busycontacts' },
              { text: 'Cal2Todo', link: '/apps/cal2todo' },
              { text: 'Calca', link: '/apps/calca' },
              { text: 'Calendar 366', link: '/apps/calendar-366' },
              { text: 'Calendars by Readdle', link: '/apps/calendars-readdle' },
              { text: 'Capacities', link: '/apps/capacities' },
              { text: 'Cardhop', link: '/apps/cardhop' },
              { text: 'Charty', link: '/apps/charty' },
              { text: 'Cherry Studio', link: '/apps/cherry-studio' },
              { text: 'Choosy', link: '/apps/choosy' },
              { text: 'Chute', link: '/apps/chute' },
              { text: 'Citymapper', link: '/apps/citymapper' },
              { text: 'CleanShot X', link: '/apps/cleanshot-x' },
              { text: 'Cloze', link: '/apps/cloze' },
              { text: 'Coda', link: '/apps/coda' },
              { text: 'CodeBuddy', link: '/apps/code-buddy' },
              { text: 'CodeBuddy China', link: '/apps/code-buddy-cn' },
              { text: 'CodeLite', link: '/apps/codelite' },
              { text: 'CodeRunner', link: '/apps/code-runner' },
              { text: 'CodeHub', link: '/apps/codehub' },
              { text: 'Codex', link: '/apps/codex' },
              { text: 'Craft', link: '/apps/craft' },
              { text: 'Cubox', link: '/apps/cubox' },
              { text: 'Cursor', link: '/apps/cursor' },
              { text: 'Dash', link: '/apps/dash' },
              { text: '2Do', link: '/apps/2do' },
              { text: 'Day One', link: '/apps/day-one' },
              { text: 'Downcast', link: '/apps/downcast' },
              { text: 'Debit & Credit', link: '/apps/debit-credit' },
              { text: 'DEVONthink', link: '/apps/devonthink' },
              { text: 'Diarly', link: '/apps/diarly' },
              { text: 'dict.cc', link: '/apps/dict-cc' },
              { text: 'Drafts', link: '/apps/drafts' },
              { text: 'Editorial', link: '/apps/editorial' },
              { text: 'Equipd Bible', link: '/apps/equipd-bible' },
              { text: 'Due', link: '/apps/due' },
              { text: 'Dynamics 365 Field Service Mobile', link: '/apps/dynamics-365-field-service-mobile' },
              { text: 'Evernote', link: '/apps/evernote' },
              { text: 'Fantastical', link: '/apps/fantastical' },
              { text: 'Claris FileMaker', link: '/apps/filemaker' },
              { text: 'Find Any File', link: '/apps/find-any-file' },
              { text: 'Focus', link: '/apps/focus' },
              { text: 'ForeFlight Mobile', link: '/apps/foreflight-mobile' },
              { text: 'forScore', link: '/apps/forscore' },
              { text: 'FSNotes', link: '/apps/fsnotes' },
              { text: 'Streets', link: '/apps/ftstreets' },
              { text: 'Fulcrum', link: '/apps/fulcrum' },
              { text: 'Gett', link: '/apps/gett' },
              { text: 'GitHub Desktop', link: '/apps/github-desktop' },
              { text: 'Gladys', link: '/apps/gladys' },
              { text: 'GoodLinks', link: '/apps/goodlinks' },
              { text: 'GoodReader', link: '/apps/goodreader' },
              { text: 'GoodTask', link: '/apps/goodtask' },
              { text: 'GoLand', link: '/apps/goland' },
              { text: 'Google Chrome iOS', link: '/apps/google-chrome-ios' },
              { text: 'Google Maps', link: '/apps/google-maps' },
              { text: 'Guru Maps', link: '/apps/guru-maps' },
              { text: 'GV Connect', link: '/apps/gv-connect' },
              { text: 'HapiGo', link: '/apps/hapigo' },
              { text: 'HBuilderX', link: '/apps/hbuilderx' },
              { text: 'Hammerspoon', link: '/apps/hammerspoon' },
              { text: 'Hiddify', link: '/apps/hiddify' },
              { text: 'Highlights', link: '/apps/highlights' },
              { text: 'Home Assistant', link: '/apps/home-assistant' },
              { text: 'Hookmark', link: '/apps/hookmark' },
              { text: 'Hot Tub', link: '/apps/hot-tub' },
              { text: 'HoudahSpot', link: '/apps/houdahspot' },
              { text: 'iA Writer', link: '/apps/ia-writer' },
              { text: 'iCab Mobile', link: '/apps/icab-mobile' },
              { text: 'IntelliJ IDEA', link: '/apps/idea' },
              { text: 'Infuse', link: '/apps/infuse' },
              { text: 'inRoute', link: '/apps/inroute' },
              { text: 'Instapaper', link: '/apps/instapaper' },
              { text: 'Interact Scratchpad', link: '/apps/interact' },
              { text: 'iPGMail', link: '/apps/ipgmail' },
              { text: 'iReal Pro', link: '/apps/ireal-pro' },
              { text: 'iThoughts', link: '/apps/ithoughts' },
              { text: 'Itsycal', link: '/apps/itsycal' },
              { text: 'Ivanti Web@Work', link: '/apps/ivanti-web-work' },
              { text: 'Ivory', link: '/apps/ivory' },
              { text: 'Joplin', link: '/apps/joplin' },
              { text: 'Jump Desktop', link: '/apps/jump-desktop' },
              { text: 'Just Timers', link: '/apps/just-timers' },
              { text: 'Kakao Map', link: '/apps/kakao-map' },
              { text: 'Keyboard Maestro', link: '/apps/keyboard-maestro' },
              { text: 'Kaleidoscope', link: '/apps/kaleidoscope' },
              { text: 'Keep It', link: '/apps/keepit' },
              { text: 'Kiro', link: '/apps/kiro' },
              { text: 'Launch Center Pro', link: '/apps/launch-center-pro' },
              { text: 'LaunchBar', link: '/apps/launchbar' },
              { text: 'Letterboxd', link: '/apps/letterboxd' },
              { text: 'LINE', link: '/apps/line' },
              { text: 'Lingma', link: '/apps/lingma' },
              { text: 'Locus Map', link: '/apps/locus-map' },
              { text: 'Longshot', link: '/apps/longshot' },
              { text: 'macOS', link: '/apps/macos' },
              { text: 'MacVim', link: '/apps/macvim' },
              { text: 'Mail Assistant', link: '/apps/mail-assistant' },
              { text: 'Marked', link: '/apps/marked' },
              { text: 'Mattermost', link: '/apps/mattermost' },
              { text: 'miCal', link: '/apps/mical' },
              { text: 'Microsoft Edge', link: '/apps/microsoft-edge' },
              { text: 'Microsoft Office', link: '/apps/microsoft-office' },
              { text: 'Microsoft OneNote', link: '/apps/microsoft-onenote' },
              { text: 'Microsoft Remote Desktop', link: '/apps/microsoft-remote-desktop' },
              { text: 'Microsoft Teams', link: '/apps/microsoft-teams' },
              { text: 'MindNode', link: '/apps/mindnode' },
              { text: 'Momento', link: '/apps/momento' },
              { text: 'MoneyWiz', link: '/apps/moneywiz' },
              { text: 'Moovit', link: '/apps/moovit' },
              { text: 'Motrix', link: '/apps/motrix' },
              { text: 'MultiTimer', link: '/apps/multi-timer' },
              { text: 'NAVER Map', link: '/apps/naver-map' },
              { text: 'Navicat', link: '/apps/navicat' },
              { text: 'NotePlan', link: '/apps/noteplan' },
              { text: 'Notebooks', link: '/apps/notebooks' },
              { text: 'Nozbe', link: '/apps/nozbe' },
              { text: 'Nova', link: '/apps/nova' },
              { text: 'Obsidian', link: '/apps/obsidian' },
              { text: 'OK JSON', link: '/apps/ok-json' },
              { text: 'OmniFocus', link: '/apps/omnifocus' },
              { text: 'OmniOutliner', link: '/apps/omnioutliner' },
              { text: 'OnSong', link: '/apps/onsong' },
              { text: 'OpenCode', link: '/apps/opencode' },
              { text: 'Opener', link: '/apps/opener' },
              { text: 'OpenVPN Connect', link: '/apps/openvpn-connect' },
              { text: 'Orchids', link: '/apps/orchids' },
              { text: 'Organic Maps', link: '/apps/organic-maps' },
              { text: 'Orion Browser', link: '/apps/orion-browser' },
              { text: 'Overcast', link: '/apps/overcast' },
              { text: 'Panorama X', link: '/apps/panorama-x' },
              { text: 'PCalc', link: '/apps/pcalc' },
              { text: 'PearAI', link: '/apps/pearai' },
              { text: 'PDF Expert', link: '/apps/pdf-expert' },
              { text: 'PDF Viewer', link: '/apps/pdf-viewer' },
              { text: 'Permute', link: '/apps/permute' },
              { text: 'Pika', link: '/apps/pika' },
              { text: 'Picsew', link: '/apps/picsew' },
              { text: 'Pincase', link: '/apps/pincase' },
              { text: 'Pleco', link: '/apps/pleco' },
              { text: 'Pocket Casts', link: '/apps/pocket-casts' },
              { text: 'Power Apps Mobile', link: '/apps/power-apps-mobile' },
              { text: 'Power BI Mobile', link: '/apps/power-bi-mobile' },
              { text: 'Postman', link: '/apps/postman' },
              { text: 'Prizmo', link: '/apps/prizmo' },
              { text: 'Pushcut', link: '/apps/pushcut' },
              { text: 'PhpStorm', link: '/apps/phpstorm' },
              { text: 'PyCharm', link: '/apps/pycharm' },
              { text: 'Pythonista', link: '/apps/pythonista' },
              { text: 'Pyto', link: '/apps/pyto' },
              { text: 'Qoder', link: '/apps/qoder' },
              { text: 'Quark', link: '/apps/quark' },
              { text: 'Raycast', link: '/apps/raycast' },
              { text: 'Remote Desktop Manager', link: '/apps/remote-desktop-manager' },
              { text: 'Reeder', link: '/apps/reeder' },
              { text: 'RingCentral', link: '/apps/ringcentral' },
              { text: 'Royal TS', link: '/apps/royal-ts' },
              { text: 'RustRover', link: '/apps/rustrover' },
              { text: 'Salesforce Mobile', link: '/apps/salesforce-mobile' },
              { text: 'Scannr', link: '/apps/scannr' },
              { text: 'Screens', link: '/apps/screens' },
              { text: 'Scriptable', link: '/apps/scriptable' },
              { text: 'Shopi', link: '/apps/shopi' },
              { text: 'Shortcuts', link: '/apps/shortcuts' },
              { text: 'Simple Scan', link: '/apps/simple-scan' },
              { text: 'Sketch', link: '/apps/sketch' },
              { text: 'Skype', link: '/apps/skype' },
              { text: 'Slack', link: '/apps/slack' },
              { text: 'Soulver', link: '/apps/soulver' },
              { text: 'Sorted³', link: '/apps/sorted' },
              { text: 'SourceTree', link: '/apps/sourcetree' },
              { text: 'Spark Mail', link: '/apps/spark' },
              { text: 'Splashtop Business', link: '/apps/splashtop-business' },
              { text: 'Spotify', link: '/apps/spotify' },
              { text: 'Steam', link: '/apps/steam' },
              { text: 'Stream Deck', link: '/apps/stream-deck' },
              { text: 'Story Planner', link: '/apps/story-planner' },
              { text: 'Surge', link: '/apps/surge' },
              { text: 'TablePro', link: '/apps/tablepro' },
              { text: 'Tadam', link: '/apps/tadam' },
              { text: 'Tally', link: '/apps/tally' },
              { text: 'Telegram', link: '/apps/telegram' },
              { text: 'Tembo', link: '/apps/tembo' },
              { text: 'Terminology', link: '/apps/terminology' },
              { text: 'Termius', link: '/apps/termius' },
              { text: 'Textastic', link: '/apps/textastic' },
              { text: 'Textwell', link: '/apps/textwell' },
              { text: 'TextMate', link: '/apps/textmate' },
              { text: 'Theia', link: '/apps/theia' },
              { text: 'Things', link: '/apps/things' },
              { text: 'Thunder', link: '/apps/thunder' },
              { text: 'Tim', link: '/apps/tim' },
              { text: 'Timing', link: '/apps/timing' },
              { text: 'Timer+', link: '/apps/timer-plus' },
              { text: 'Timepage', link: '/apps/timepage' },
              { text: 'Today Habit Tracker', link: '/apps/today-habit-tracker' },
              { text: 'Todoist', link: '/apps/todoist' },
              { text: 'Tower', link: '/apps/tower' },
              { text: 'Trae', link: '/apps/trae' },
              { text: 'Trae China', link: '/apps/trae-cn' },
              { text: 'Trello', link: '/apps/trello' },
              { text: 'TrueContext', link: '/apps/truecontext' },
              { text: 'Ulysses', link: '/apps/ulysses' },
              { text: 'uPic', link: '/apps/upic' },
              { text: 'UpNote', link: '/apps/upnote' },
              { text: 'Verdent', link: '/apps/verdent' },
              { text: 'Viber', link: '/apps/viber' },
              { text: 'VS Code', link: '/apps/vscode' },
              { text: 'VS Code Insiders', link: '/apps/vscode-insiders' },
              { text: 'VSCodium', link: '/apps/vscodium' },
              { text: 'Warp', link: '/apps/warp' },
              { text: 'WaterMinder', link: '/apps/waterminder' },
              { text: 'Waze', link: '/apps/waze' },
              { text: 'Webex', link: '/apps/webex' },
              { text: 'WebStorm', link: '/apps/webstorm' },
              { text: 'WeMeet', link: '/apps/wemeet' },
              { text: 'what3words', link: '/apps/what3words' },
              { text: 'Where To', link: '/apps/whereto' },
              { text: 'Windsurf', link: '/apps/windsurf' },
              { text: 'Working Copy', link: '/apps/working-copy' },
              { text: 'Written Down', link: '/apps/written-down' },
              { text: 'Xcode', link: '/apps/xcode' },
              { text: 'Yandex Maps', link: '/apps/yandex-maps' },
              { text: 'Yandex Navigator', link: '/apps/yandex-navigator' },
              { text: 'Yoink for iOS', link: '/apps/yoink-ios' },
              { text: 'Zed', link: '/apps/zed' },
              { text: 'Zoom', link: '/apps/zoom' },
            ],
          },
          {
            text: '简介',
            base: '',
            items: [
              { text: '什么是 Protocol Launcher？', link: '/zh/guide/what-is-it' },
              { text: '快速开始', link: '/zh/guide/getting-started' },
            ],
          },
          {
            text: '应用程序',
            base: '',
            items: [
              { text: 'AFFiNE', link: '/zh/apps/affine' },
              { text: 'Agenda', link: '/zh/apps/agenda' },
              { text: 'Airmail', link: '/zh/apps/airmail' },
              { text: 'Alfred', link: '/zh/apps/alfred' },
              { text: 'Alter', link: '/zh/apps/alter' },
              { text: 'Antigravity', link: '/zh/apps/antigravity' },
              { text: 'Anybox', link: '/zh/apps/anybox' },
              { text: 'AnyDesk', link: '/zh/apps/anydesk' },
              { text: 'App Store', link: '/zh/apps/app-store' },
              { text: 'AppFlowy', link: '/zh/apps/appflowy' },
              { text: 'Appigo Todo', link: '/zh/apps/appigo-todo' },
              { text: 'Apple 地图', link: '/zh/apps/apple-map' },
              { text: 'Apple Script Editor', link: '/zh/apps/apple-script' },
              { text: 'ArcGIS QuickCapture', link: '/zh/apps/arcgis-quickcapture' },
              { text: 'ArcGIS Survey123', link: '/zh/apps/arcgis-survey123' },
              { text: 'Atom', link: '/zh/apps/atom' },
              { text: '1Writer', link: '/zh/apps/1writer' },
              { text: 'BarCuts', link: '/zh/apps/barcuts' },
              { text: 'BBEdit', link: '/zh/apps/bbedit' },
              { text: 'Bear', link: '/zh/apps/bear' },
              { text: 'Beorg', link: '/zh/apps/beorg' },
              { text: 'BetterTouchTool', link: '/zh/apps/bettertouchtool' },
              { text: 'Bike Outliner', link: '/zh/apps/bike-outliner' },
              { text: 'Box', link: '/zh/apps/box' },
              { text: 'Buchen', link: '/zh/apps/buchen' },
              { text: 'Bunch', link: '/zh/apps/bunch' },
              { text: 'BusyCal', link: '/zh/apps/busycal' },
              { text: 'BusyContacts', link: '/zh/apps/busycontacts' },
              { text: 'Cal2Todo', link: '/zh/apps/cal2todo' },
              { text: 'Calca', link: '/zh/apps/calca' },
              { text: 'Calendar 366', link: '/zh/apps/calendar-366' },
              { text: 'Calendars by Readdle', link: '/zh/apps/calendars-readdle' },
              { text: 'Capacities', link: '/zh/apps/capacities' },
              { text: 'Cardhop', link: '/zh/apps/cardhop' },
              { text: 'Charty', link: '/zh/apps/charty' },
              { text: 'Cherry Studio', link: '/zh/apps/cherry-studio' },
              { text: 'Choosy', link: '/zh/apps/choosy' },
              { text: 'Chute', link: '/zh/apps/chute' },
              { text: 'Citymapper', link: '/zh/apps/citymapper' },
              { text: 'CleanShot X', link: '/zh/apps/cleanshot-x' },
              { text: 'Cloze', link: '/zh/apps/cloze' },
              { text: 'Coda', link: '/zh/apps/coda' },
              { text: 'CodeBuddy', link: '/zh/apps/code-buddy' },
              { text: 'CodeBuddy China', link: '/zh/apps/code-buddy-cn' },
              { text: 'CodeLite', link: '/zh/apps/codelite' },
              { text: 'CodeRunner', link: '/zh/apps/code-runner' },
              { text: 'CodeHub', link: '/zh/apps/codehub' },
              { text: 'Codex', link: '/zh/apps/codex' },
              { text: 'Craft', link: '/zh/apps/craft' },
              { text: 'Cubox', link: '/zh/apps/cubox' },
              { text: 'Cursor', link: '/zh/apps/cursor' },
              { text: 'Dash', link: '/zh/apps/dash' },
              { text: '2Do', link: '/zh/apps/2do' },
              { text: 'Day One', link: '/zh/apps/day-one' },
              { text: 'Downcast', link: '/zh/apps/downcast' },
              { text: 'Debit & Credit', link: '/zh/apps/debit-credit' },
              { text: 'DEVONthink', link: '/zh/apps/devonthink' },
              { text: 'Diarly', link: '/zh/apps/diarly' },
              { text: 'dict.cc', link: '/zh/apps/dict-cc' },
              { text: 'Drafts', link: '/zh/apps/drafts' },
              { text: 'Editorial', link: '/zh/apps/editorial' },
              { text: 'Equipd Bible', link: '/zh/apps/equipd-bible' },
              { text: 'Due', link: '/zh/apps/due' },
              { text: 'Dynamics 365 Field Service Mobile', link: '/zh/apps/dynamics-365-field-service-mobile' },
              { text: 'Evernote', link: '/zh/apps/evernote' },
              { text: 'Fantastical', link: '/zh/apps/fantastical' },
              { text: 'Claris FileMaker', link: '/zh/apps/filemaker' },
              { text: 'Find Any File', link: '/zh/apps/find-any-file' },
              { text: 'Focus', link: '/zh/apps/focus' },
              { text: 'ForeFlight Mobile', link: '/zh/apps/foreflight-mobile' },
              { text: 'forScore', link: '/zh/apps/forscore' },
              { text: 'FSNotes', link: '/zh/apps/fsnotes' },
              { text: 'Streets', link: '/zh/apps/ftstreets' },
              { text: 'Fulcrum', link: '/zh/apps/fulcrum' },
              { text: 'Gett', link: '/zh/apps/gett' },
              { text: 'GitHub Desktop', link: '/zh/apps/github-desktop' },
              { text: 'Gladys', link: '/zh/apps/gladys' },
              { text: 'GoodLinks', link: '/zh/apps/goodlinks' },
              { text: 'GoodReader', link: '/zh/apps/goodreader' },
              { text: 'GoodTask', link: '/zh/apps/goodtask' },
              { text: 'GoLand', link: '/zh/apps/goland' },
              { text: 'Google Chrome iOS', link: '/zh/apps/google-chrome-ios' },
              { text: 'Google Maps', link: '/zh/apps/google-maps' },
              { text: 'Guru Maps', link: '/zh/apps/guru-maps' },
              { text: 'GV Connect', link: '/zh/apps/gv-connect' },
              { text: 'HapiGo', link: '/zh/apps/hapigo' },
              { text: 'HBuilderX', link: '/zh/apps/hbuilderx' },
              { text: 'Hammerspoon', link: '/zh/apps/hammerspoon' },
              { text: 'Hiddify', link: '/zh/apps/hiddify' },
              { text: 'Highlights', link: '/zh/apps/highlights' },
              { text: 'Home Assistant', link: '/zh/apps/home-assistant' },
              { text: 'Hookmark', link: '/zh/apps/hookmark' },
              { text: 'Hot Tub', link: '/zh/apps/hot-tub' },
              { text: 'HoudahSpot', link: '/zh/apps/houdahspot' },
              { text: 'iA Writer', link: '/zh/apps/ia-writer' },
              { text: 'iCab Mobile', link: '/zh/apps/icab-mobile' },
              { text: 'IntelliJ IDEA', link: '/zh/apps/idea' },
              { text: 'Infuse', link: '/zh/apps/infuse' },
              { text: 'inRoute', link: '/zh/apps/inroute' },
              { text: 'Instapaper', link: '/zh/apps/instapaper' },
              { text: 'Interact Scratchpad', link: '/zh/apps/interact' },
              { text: 'iPGMail', link: '/zh/apps/ipgmail' },
              { text: 'iReal Pro', link: '/zh/apps/ireal-pro' },
              { text: 'iThoughts', link: '/zh/apps/ithoughts' },
              { text: 'Itsycal', link: '/zh/apps/itsycal' },
              { text: 'Ivanti Web@Work', link: '/zh/apps/ivanti-web-work' },
              { text: 'Ivory', link: '/zh/apps/ivory' },
              { text: 'Joplin', link: '/zh/apps/joplin' },
              { text: 'Jump Desktop', link: '/zh/apps/jump-desktop' },
              { text: 'Just Timers', link: '/zh/apps/just-timers' },
              { text: 'Kakao Map', link: '/zh/apps/kakao-map' },
              { text: 'Keyboard Maestro', link: '/zh/apps/keyboard-maestro' },
              { text: 'Kaleidoscope', link: '/zh/apps/kaleidoscope' },
              { text: 'Keep It', link: '/zh/apps/keepit' },
              { text: 'Kiro', link: '/zh/apps/kiro' },
              { text: 'Launch Center Pro', link: '/zh/apps/launch-center-pro' },
              { text: 'LaunchBar', link: '/zh/apps/launchbar' },
              { text: 'Letterboxd', link: '/zh/apps/letterboxd' },
              { text: 'LINE', link: '/zh/apps/line' },
              { text: 'Lingma', link: '/zh/apps/lingma' },
              { text: 'Locus Map', link: '/zh/apps/locus-map' },
              { text: 'Longshot', link: '/zh/apps/longshot' },
              { text: 'macOS', link: '/zh/apps/macos' },
              { text: 'MacVim', link: '/zh/apps/macvim' },
              { text: 'Mail Assistant', link: '/zh/apps/mail-assistant' },
              { text: 'Marked', link: '/zh/apps/marked' },
              { text: 'Mattermost', link: '/zh/apps/mattermost' },
              { text: 'miCal', link: '/zh/apps/mical' },
              { text: 'Microsoft Edge', link: '/zh/apps/microsoft-edge' },
              { text: 'Microsoft Office', link: '/zh/apps/microsoft-office' },
              { text: 'Microsoft OneNote', link: '/zh/apps/microsoft-onenote' },
              { text: 'Microsoft Remote Desktop', link: '/zh/apps/microsoft-remote-desktop' },
              { text: 'Microsoft Teams', link: '/zh/apps/microsoft-teams' },
              { text: 'MindNode', link: '/zh/apps/mindnode' },
              { text: 'Momento', link: '/zh/apps/momento' },
              { text: 'MoneyWiz', link: '/zh/apps/moneywiz' },
              { text: 'Moovit', link: '/zh/apps/moovit' },
              { text: 'Motrix', link: '/zh/apps/motrix' },
              { text: 'MultiTimer', link: '/zh/apps/multi-timer' },
              { text: 'NAVER Map', link: '/zh/apps/naver-map' },
              { text: 'Navicat', link: '/zh/apps/navicat' },
              { text: 'NotePlan', link: '/zh/apps/noteplan' },
              { text: 'Notebooks', link: '/zh/apps/notebooks' },
              { text: 'Nozbe', link: '/zh/apps/nozbe' },
              { text: 'Nova', link: '/zh/apps/nova' },
              { text: 'Obsidian', link: '/zh/apps/obsidian' },
              { text: 'OK JSON', link: '/zh/apps/ok-json' },
              { text: 'OmniFocus', link: '/zh/apps/omnifocus' },
              { text: 'OmniOutliner', link: '/zh/apps/omnioutliner' },
              { text: 'OnSong', link: '/zh/apps/onsong' },
              { text: 'OpenCode', link: '/zh/apps/opencode' },
              { text: 'Opener', link: '/zh/apps/opener' },
              { text: 'OpenVPN Connect', link: '/zh/apps/openvpn-connect' },
              { text: 'Orchids', link: '/zh/apps/orchids' },
              { text: 'Organic Maps', link: '/zh/apps/organic-maps' },
              { text: 'Orion Browser', link: '/zh/apps/orion-browser' },
              { text: 'Overcast', link: '/zh/apps/overcast' },
              { text: 'Panorama X', link: '/zh/apps/panorama-x' },
              { text: 'PCalc', link: '/zh/apps/pcalc' },
              { text: 'PearAI', link: '/zh/apps/pearai' },
              { text: 'PDF Expert', link: '/zh/apps/pdf-expert' },
              { text: 'PDF Viewer', link: '/zh/apps/pdf-viewer' },
              { text: 'Permute', link: '/zh/apps/permute' },
              { text: 'Pika', link: '/zh/apps/pika' },
              { text: 'Picsew', link: '/zh/apps/picsew' },
              { text: 'Pincase', link: '/zh/apps/pincase' },
              { text: 'Pleco', link: '/zh/apps/pleco' },
              { text: 'Pocket Casts', link: '/zh/apps/pocket-casts' },
              { text: 'Power Apps Mobile', link: '/zh/apps/power-apps-mobile' },
              { text: 'Power BI Mobile', link: '/zh/apps/power-bi-mobile' },
              { text: 'Postman', link: '/zh/apps/postman' },
              { text: 'Prizmo', link: '/zh/apps/prizmo' },
              { text: 'Pushcut', link: '/zh/apps/pushcut' },
              { text: 'PhpStorm', link: '/zh/apps/phpstorm' },
              { text: 'PyCharm', link: '/zh/apps/pycharm' },
              { text: 'Pythonista', link: '/zh/apps/pythonista' },
              { text: 'Pyto', link: '/zh/apps/pyto' },
              { text: 'Qoder', link: '/zh/apps/qoder' },
              { text: 'Quark', link: '/zh/apps/quark' },
              { text: 'Raycast', link: '/zh/apps/raycast' },
              { text: 'Remote Desktop Manager', link: '/zh/apps/remote-desktop-manager' },
              { text: 'Reeder', link: '/zh/apps/reeder' },
              { text: 'RingCentral', link: '/zh/apps/ringcentral' },
              { text: 'Royal TS', link: '/zh/apps/royal-ts' },
              { text: 'RustRover', link: '/zh/apps/rustrover' },
              { text: 'Salesforce Mobile', link: '/zh/apps/salesforce-mobile' },
              { text: 'Scannr', link: '/zh/apps/scannr' },
              { text: 'Screens', link: '/zh/apps/screens' },
              { text: 'Scriptable', link: '/zh/apps/scriptable' },
              { text: 'Shopi', link: '/zh/apps/shopi' },
              { text: 'Shortcuts', link: '/zh/apps/shortcuts' },
              { text: 'Simple Scan', link: '/zh/apps/simple-scan' },
              { text: 'Sketch', link: '/zh/apps/sketch' },
              { text: 'Skype', link: '/zh/apps/skype' },
              { text: 'Slack', link: '/zh/apps/slack' },
              { text: 'Soulver', link: '/zh/apps/soulver' },
              { text: 'Sorted³', link: '/zh/apps/sorted' },
              { text: 'SourceTree', link: '/zh/apps/sourcetree' },
              { text: 'Spark Mail', link: '/zh/apps/spark' },
              { text: 'Splashtop Business', link: '/zh/apps/splashtop-business' },
              { text: 'Spotify', link: '/zh/apps/spotify' },
              { text: 'Steam', link: '/zh/apps/steam' },
              { text: 'Stream Deck', link: '/zh/apps/stream-deck' },
              { text: 'Story Planner', link: '/zh/apps/story-planner' },
              { text: 'Surge', link: '/zh/apps/surge' },
              { text: 'TablePro', link: '/zh/apps/tablepro' },
              { text: 'Tadam', link: '/zh/apps/tadam' },
              { text: 'Tally', link: '/zh/apps/tally' },
              { text: 'Telegram', link: '/zh/apps/telegram' },
              { text: 'Tembo', link: '/zh/apps/tembo' },
              { text: 'Terminology', link: '/zh/apps/terminology' },
              { text: 'Termius', link: '/zh/apps/termius' },
              { text: 'Textastic', link: '/zh/apps/textastic' },
              { text: 'Textwell', link: '/zh/apps/textwell' },
              { text: 'TextMate', link: '/zh/apps/textmate' },
              { text: 'Theia', link: '/zh/apps/theia' },
              { text: 'Things', link: '/zh/apps/things' },
              { text: 'Thunder', link: '/zh/apps/thunder' },
              { text: 'Tim', link: '/zh/apps/tim' },
              { text: 'Timing', link: '/zh/apps/timing' },
              { text: 'Timer+', link: '/zh/apps/timer-plus' },
              { text: 'Timepage', link: '/zh/apps/timepage' },
              { text: 'Today Habit Tracker', link: '/zh/apps/today-habit-tracker' },
              { text: 'Todoist', link: '/zh/apps/todoist' },
              { text: 'Tower', link: '/zh/apps/tower' },
              { text: 'Trae', link: '/zh/apps/trae' },
              { text: 'Trae China', link: '/zh/apps/trae-cn' },
              { text: 'Trello', link: '/zh/apps/trello' },
              { text: 'TrueContext', link: '/zh/apps/truecontext' },
              { text: 'Ulysses', link: '/zh/apps/ulysses' },
              { text: 'uPic', link: '/zh/apps/upic' },
              { text: 'UpNote', link: '/zh/apps/upnote' },
              { text: 'Verdent', link: '/zh/apps/verdent' },
              { text: 'Viber', link: '/zh/apps/viber' },
              { text: 'VS Code', link: '/zh/apps/vscode' },
              { text: 'VS Code Insiders', link: '/zh/apps/vscode-insiders' },
              { text: 'VSCodium', link: '/zh/apps/vscodium' },
              { text: 'Warp', link: '/zh/apps/warp' },
              { text: 'WaterMinder', link: '/zh/apps/waterminder' },
              { text: 'Waze', link: '/zh/apps/waze' },
              { text: 'Webex', link: '/zh/apps/webex' },
              { text: 'WebStorm', link: '/zh/apps/webstorm' },
              { text: 'WeMeet', link: '/zh/apps/wemeet' },
              { text: 'what3words', link: '/zh/apps/what3words' },
              { text: 'Where To', link: '/zh/apps/whereto' },
              { text: 'Windsurf', link: '/zh/apps/windsurf' },
              { text: 'Working Copy', link: '/zh/apps/working-copy' },
              { text: 'Written Down', link: '/zh/apps/written-down' },
              { text: 'Xcode', link: '/zh/apps/xcode' },
              { text: 'Yandex Maps', link: '/zh/apps/yandex-maps' },
              { text: 'Yandex Navigator', link: '/zh/apps/yandex-navigator' },
              { text: 'Yoink for iOS', link: '/zh/apps/yoink-ios' },
              { text: 'Zed', link: '/zh/apps/zed' },
              { text: 'Zoom', link: '/zh/apps/zoom' },
            ],
          },
          {
            text: '扩展',
            base: '',
            items: [{ text: '示例', link: '/zh/extra/examples' }],
          },
        ],
        details: `\
- 🛡️ Type-Safe
- 🧩 Multi-App Ready
- 🔬 On-Demand / Tree-shakable
- 🔐 Secure Encoding (safe configs, Unicode)
- ⚙️ Zero Runtime Dependencies
- 📦 ESM First
- 🚀 One-click deep links to trigger app actions
`,
      }),
      // https://icon-sets.iconify.design/logos/?keyword=logos
      // https://icon-sets.iconify.design/vscode-icons/?keyword=vscode-icons
      groupIconVitePlugin({
        customIcon: {
          'cherry studio': localIconLoader(import.meta.url, '../public/app-logos/cherry-studio.svg'),
          codebuddy: localIconLoader(import.meta.url, '../public/app-logos/code-buddy.svg'),
          cursor: localIconLoader(import.meta.url, '../public/app-logos/cursor.svg'),
          'github desktop': 'logos:github-octocat',
          goland: 'logos:goland',
          idea: 'logos:intellij-idea',
          phpstorm: 'logos:phpstorm',
          pycharm: 'logos:pycharm',
          rustrover: 'logos:rust',
          telegram: 'logos:telegram',
          thunder: localIconLoader(import.meta.url, '../public/app-logos/thunder.svg'),
          vscode: 'vscode-icons:file-type-vscode',
          webstorm: 'logos:webstorm',
          xcode: 'logos:xcode',
        },
      }),
    ],
  },
})
