import { type AlterActionCallbackUrl, appendAlterInput } from './shared'

export interface RunGeneratedActionPayload {
  /**
   * Alter action callback URL copied from the Action Editor.
   *
   * @example 'alter://action/ask-web'
   */
  url: AlterActionCallbackUrl

  /**
   * Optional input passed through the official `input` query parameter.
   *
   * @example 'What is Alter MacOS'
   */
  input?: string
}

/**
 * Run an Alter action callback URL generated by Alter, optionally passing input data.
 *
 * @param payload Alter generated action payload.
 * @returns Alter action callback URL.
 * @example
 * runGeneratedAction({ url: 'alter://action/ask-web', input: 'What is Alter MacOS' })
 * // => 'alter://action/ask-web?input=What+is+Alter+MacOS'
 * @link https://docs.alterhq.com/workflows/url-callbacks
 */
export function runGeneratedAction(payload: RunGeneratedActionPayload) {
  const { url, input } = payload

  if (input === undefined) return url

  return appendAlterInput(url, input)
}
