import { type DefaultTheme, defineAdditionalConfig } from 'vitepress'
import pkg from '../../../packages/protocol-launcher/package.json' with { type: 'json' }

// https://vitepress.dev/reference/site-config
export default defineAdditionalConfig({
  description: '面向多种协议应用的一键启动链接生成器',
  themeConfig: {
    nav: [
      { text: '首页', link: '/zh/' },
      { text: '指南', link: '/zh/guide/getting-started', activeMatch: '/guide/' },
      {
        text: pkg.version,
        items: [
          {
            text: 'Changelog',
            link: 'https://github.com/zhensherlock/protocol-launcher/blob/main/packages/protocol-launcher/CHANGELOG.md',
          },
        ],
      },
    ],

    sidebar: [
      {
        text: '简介',
        items: [
          { text: '什么是 Protocol Launcher？', link: '/zh/guide/what-is-it' },
          { text: '快速开始', link: '/zh/guide/getting-started' },
        ],
      },
      {
        text: '应用程序',
        items: [
          { text: 'AFFiNE', link: '/zh/apps/affine' },
          { text: 'Agenda', link: '/zh/apps/agenda' },
          { text: 'Airmail', link: '/zh/apps/airmail' },
          { text: 'Alfred', link: '/zh/apps/alfred' },
          { text: 'Alter', link: '/zh/apps/alter' },
          { text: 'Antigravity', link: '/zh/apps/antigravity' },
          { text: 'Anybox', link: '/zh/apps/anybox' },
          { text: 'AnyDesk', link: '/zh/apps/anydesk' },
          { text: 'App Store', link: '/zh/apps/app-store' },
          { text: 'AppFlowy', link: '/zh/apps/appflowy' },
          { text: 'Appigo Todo', link: '/zh/apps/appigo-todo' },
          { text: 'Apple 地图', link: '/zh/apps/apple-map' },
          { text: 'Apple Script Editor', link: '/zh/apps/apple-script' },
          { text: 'ArcGIS QuickCapture', link: '/zh/apps/arcgis-quickcapture' },
          { text: 'ArcGIS Survey123', link: '/zh/apps/arcgis-survey123' },
          { text: 'Atom', link: '/zh/apps/atom' },
          { text: '1Writer', link: '/zh/apps/1writer' },
          { text: 'BarCuts', link: '/zh/apps/barcuts' },
          { text: 'BBEdit', link: '/zh/apps/bbedit' },
          { text: 'Bear', link: '/zh/apps/bear' },
          { text: 'Beorg', link: '/zh/apps/beorg' },
          { text: 'BetterTouchTool', link: '/zh/apps/bettertouchtool' },
          { text: 'Bike Outliner', link: '/zh/apps/bike-outliner' },
          { text: 'Box', link: '/zh/apps/box' },
          { text: 'Buchen', link: '/zh/apps/buchen' },
          { text: 'Bunch', link: '/zh/apps/bunch' },
          { text: 'BusyCal', link: '/zh/apps/busycal' },
          { text: 'BusyContacts', link: '/zh/apps/busycontacts' },
          { text: 'Cal2Todo', link: '/zh/apps/cal2todo' },
          { text: 'Calca', link: '/zh/apps/calca' },
          { text: 'Calendar 366', link: '/zh/apps/calendar-366' },
          { text: 'Calendars by Readdle', link: '/zh/apps/calendars-readdle' },
          { text: 'Capacities', link: '/zh/apps/capacities' },
          { text: 'Cardhop', link: '/zh/apps/cardhop' },
          { text: 'Charty', link: '/zh/apps/charty' },
          { text: 'Cherry Studio', link: '/zh/apps/cherry-studio' },
          { text: 'Choosy', link: '/zh/apps/choosy' },
          { text: 'Chute', link: '/zh/apps/chute' },
          { text: 'Citymapper', link: '/zh/apps/citymapper' },
          { text: 'CleanShot X', link: '/zh/apps/cleanshot-x' },
          { text: 'Cloze', link: '/zh/apps/cloze' },
          { text: 'Coda', link: '/zh/apps/coda' },
          { text: 'CodeBuddy', link: '/zh/apps/code-buddy' },
          { text: 'CodeBuddy China', link: '/zh/apps/code-buddy-cn' },
          { text: 'CodeLite', link: '/zh/apps/codelite' },
          { text: 'CodeRunner', link: '/zh/apps/code-runner' },
          { text: 'CodeHub', link: '/zh/apps/codehub' },
          { text: 'Codex', link: '/zh/apps/codex' },
          { text: 'Craft', link: '/zh/apps/craft' },
          { text: 'Cubox', link: '/zh/apps/cubox' },
          { text: 'Cursor', link: '/zh/apps/cursor' },
          { text: 'Dash', link: '/zh/apps/dash' },
          { text: '2Do', link: '/zh/apps/2do' },
          { text: 'Day One', link: '/zh/apps/day-one' },
          { text: 'Downcast', link: '/zh/apps/downcast' },
          { text: 'Debit & Credit', link: '/zh/apps/debit-credit' },
          { text: 'DEVONthink', link: '/zh/apps/devonthink' },
          { text: 'Diarly', link: '/zh/apps/diarly' },
          { text: 'dict.cc', link: '/zh/apps/dict-cc' },
          { text: 'Documents by Readdle', link: '/zh/apps/documents-readdle' },
          { text: 'Drafts', link: '/zh/apps/drafts' },
          { text: 'Editorial', link: '/zh/apps/editorial' },
          { text: 'Equipd Bible', link: '/zh/apps/equipd-bible' },
          { text: 'Due', link: '/zh/apps/due' },
          { text: 'Dynamics 365 Field Service Mobile', link: '/zh/apps/dynamics-365-field-service-mobile' },
          { text: 'Evernote', link: '/zh/apps/evernote' },
          { text: 'Fantastical', link: '/zh/apps/fantastical' },
          { text: 'Claris FileMaker', link: '/zh/apps/filemaker' },
          { text: 'Find Any File', link: '/zh/apps/find-any-file' },
          { text: 'Focus', link: '/zh/apps/focus' },
          { text: 'ForeFlight Mobile', link: '/zh/apps/foreflight-mobile' },
          { text: 'forScore', link: '/zh/apps/forscore' },
          { text: 'FSNotes', link: '/zh/apps/fsnotes' },
          { text: 'Streets', link: '/zh/apps/ftstreets' },
          { text: 'Fulcrum', link: '/zh/apps/fulcrum' },
          { text: 'Gett', link: '/zh/apps/gett' },
          { text: 'GitHub Desktop', link: '/zh/apps/github-desktop' },
          { text: 'Gladys', link: '/zh/apps/gladys' },
          { text: 'GoodLinks', link: '/zh/apps/goodlinks' },
          { text: 'GoodReader', link: '/zh/apps/goodreader' },
          { text: 'GoodTask', link: '/zh/apps/goodtask' },
          { text: 'GoLand', link: '/zh/apps/goland' },
          { text: 'Google Chrome iOS', link: '/zh/apps/google-chrome-ios' },
          { text: 'Google Maps', link: '/zh/apps/google-maps' },
          { text: 'Guru Maps', link: '/zh/apps/guru-maps' },
          { text: 'GV Connect', link: '/zh/apps/gv-connect' },
          { text: 'HapiGo', link: '/zh/apps/hapigo' },
          { text: 'HBuilderX', link: '/zh/apps/hbuilderx' },
          { text: 'Hammerspoon', link: '/zh/apps/hammerspoon' },
          { text: 'Hiddify', link: '/zh/apps/hiddify' },
          { text: 'Highlights', link: '/zh/apps/highlights' },
          { text: 'Home Assistant', link: '/zh/apps/home-assistant' },
          { text: 'Hookmark', link: '/zh/apps/hookmark' },
          { text: 'Hot Tub', link: '/zh/apps/hot-tub' },
          { text: 'HoudahSpot', link: '/zh/apps/houdahspot' },
          { text: 'iA Writer', link: '/zh/apps/ia-writer' },
          { text: 'iCab Mobile', link: '/zh/apps/icab-mobile' },
          { text: 'IntelliJ IDEA', link: '/zh/apps/idea' },
          { text: 'Infuse', link: '/zh/apps/infuse' },
          { text: 'inRoute', link: '/zh/apps/inroute' },
          { text: 'Instapaper', link: '/zh/apps/instapaper' },
          { text: 'Interact Scratchpad', link: '/zh/apps/interact' },
          { text: 'iPGMail', link: '/zh/apps/ipgmail' },
          { text: 'iReal Pro', link: '/zh/apps/ireal-pro' },
          { text: 'iThoughts', link: '/zh/apps/ithoughts' },
          { text: 'Itsycal', link: '/zh/apps/itsycal' },
          { text: 'Ivanti Web@Work', link: '/zh/apps/ivanti-web-work' },
          { text: 'Ivory', link: '/zh/apps/ivory' },
          { text: 'Joplin', link: '/zh/apps/joplin' },
          { text: 'Jump Desktop', link: '/zh/apps/jump-desktop' },
          { text: 'Just Timers', link: '/zh/apps/just-timers' },
          { text: 'Kakao Map', link: '/zh/apps/kakao-map' },
          { text: 'Keyboard Maestro', link: '/zh/apps/keyboard-maestro' },
          { text: 'Kaleidoscope', link: '/zh/apps/kaleidoscope' },
          { text: 'Keep It', link: '/zh/apps/keepit' },
          { text: 'Kiro', link: '/zh/apps/kiro' },
          { text: 'Launch Center Pro', link: '/zh/apps/launch-center-pro' },
          { text: 'LaunchBar', link: '/zh/apps/launchbar' },
          { text: 'Letterboxd', link: '/zh/apps/letterboxd' },
          { text: 'LINE', link: '/zh/apps/line' },
          { text: 'Lingma', link: '/zh/apps/lingma' },
          { text: 'Locus Map', link: '/zh/apps/locus-map' },
          { text: 'Longshot', link: '/zh/apps/longshot' },
          { text: 'macOS', link: '/zh/apps/macos' },
          { text: 'MacVim', link: '/zh/apps/macvim' },
          { text: 'Mail Assistant', link: '/zh/apps/mail-assistant' },
          { text: 'Marked', link: '/zh/apps/marked' },
          { text: 'Mattermost', link: '/zh/apps/mattermost' },
          { text: 'miCal', link: '/zh/apps/mical' },
          { text: 'Microsoft Edge', link: '/zh/apps/microsoft-edge' },
          { text: 'Microsoft Office', link: '/zh/apps/microsoft-office' },
          { text: 'Microsoft OneNote', link: '/zh/apps/microsoft-onenote' },
          { text: 'Microsoft Remote Desktop', link: '/zh/apps/microsoft-remote-desktop' },
          { text: 'Microsoft Teams', link: '/zh/apps/microsoft-teams' },
          { text: 'MindNode', link: '/zh/apps/mindnode' },
          { text: 'Momento', link: '/zh/apps/momento' },
          { text: 'MoneyWiz', link: '/zh/apps/moneywiz' },
          { text: 'Moovit', link: '/zh/apps/moovit' },
          { text: 'Motrix', link: '/zh/apps/motrix' },
          { text: 'MultiTimer', link: '/zh/apps/multi-timer' },
          { text: 'NAVER Map', link: '/zh/apps/naver-map' },
          { text: 'Navicat', link: '/zh/apps/navicat' },
          { text: 'NotePlan', link: '/zh/apps/noteplan' },
          { text: 'Notebooks', link: '/zh/apps/notebooks' },
          { text: 'Nozbe', link: '/zh/apps/nozbe' },
          { text: 'Nova', link: '/zh/apps/nova' },
          { text: 'Obsidian', link: '/zh/apps/obsidian' },
          { text: 'OK JSON', link: '/zh/apps/ok-json' },
          { text: 'OmniFocus', link: '/zh/apps/omnifocus' },
          { text: 'OmniOutliner', link: '/zh/apps/omnioutliner' },
          { text: 'OnSong', link: '/zh/apps/onsong' },
          { text: 'OpenCode', link: '/zh/apps/opencode' },
          { text: 'Opener', link: '/zh/apps/opener' },
          { text: 'OpenVPN Connect', link: '/zh/apps/openvpn-connect' },
          { text: 'Orchids', link: '/zh/apps/orchids' },
          { text: 'Organic Maps', link: '/zh/apps/organic-maps' },
          { text: 'Orion Browser', link: '/zh/apps/orion-browser' },
          { text: 'Overcast', link: '/zh/apps/overcast' },
          { text: 'Panorama X', link: '/zh/apps/panorama-x' },
          { text: 'PCalc', link: '/zh/apps/pcalc' },
          { text: 'PearAI', link: '/zh/apps/pearai' },
          { text: 'PDF Expert', link: '/zh/apps/pdf-expert' },
          { text: 'PDF Viewer', link: '/zh/apps/pdf-viewer' },
          { text: 'Permute', link: '/zh/apps/permute' },
          { text: 'Pika', link: '/zh/apps/pika' },
          { text: 'Picsew', link: '/zh/apps/picsew' },
          { text: 'Pincase', link: '/zh/apps/pincase' },
          { text: 'Pleco', link: '/zh/apps/pleco' },
          { text: 'Pocket Casts', link: '/zh/apps/pocket-casts' },
          { text: 'Power Apps Mobile', link: '/zh/apps/power-apps-mobile' },
          { text: 'Power BI Mobile', link: '/zh/apps/power-bi-mobile' },
          { text: 'Postman', link: '/zh/apps/postman' },
          { text: 'Prizmo', link: '/zh/apps/prizmo' },
          { text: 'Pushcut', link: '/zh/apps/pushcut' },
          { text: 'PhpStorm', link: '/zh/apps/phpstorm' },
          { text: 'PyCharm', link: '/zh/apps/pycharm' },
          { text: 'Pythonista', link: '/zh/apps/pythonista' },
          { text: 'Pyto', link: '/zh/apps/pyto' },
          { text: 'Qoder', link: '/zh/apps/qoder' },
          { text: 'Quark', link: '/zh/apps/quark' },
          { text: 'Raycast', link: '/zh/apps/raycast' },
          { text: 'Remote Desktop Manager', link: '/zh/apps/remote-desktop-manager' },
          { text: 'Reeder', link: '/zh/apps/reeder' },
          { text: 'RingCentral', link: '/zh/apps/ringcentral' },
          { text: 'Royal TS', link: '/zh/apps/royal-ts' },
          { text: 'RustRover', link: '/zh/apps/rustrover' },
          { text: 'Salesforce Mobile', link: '/zh/apps/salesforce-mobile' },
          { text: 'Scannr', link: '/zh/apps/scannr' },
          { text: 'Screens', link: '/zh/apps/screens' },
          { text: 'Scriptable', link: '/zh/apps/scriptable' },
          { text: 'Shopi', link: '/zh/apps/shopi' },
          { text: 'Shortcuts', link: '/zh/apps/shortcuts' },
          { text: 'Simple Scan', link: '/zh/apps/simple-scan' },
          { text: 'Sketch', link: '/zh/apps/sketch' },
          { text: 'Skype', link: '/zh/apps/skype' },
          { text: 'Slack', link: '/zh/apps/slack' },
          { text: 'Soulver', link: '/zh/apps/soulver' },
          { text: 'Sorted³', link: '/zh/apps/sorted' },
          { text: 'SourceTree', link: '/zh/apps/sourcetree' },
          { text: 'Spark Mail', link: '/zh/apps/spark' },
          { text: 'Splashtop Business', link: '/zh/apps/splashtop-business' },
          { text: 'Spotify', link: '/zh/apps/spotify' },
          { text: 'Steam', link: '/zh/apps/steam' },
          { text: 'Stream Deck', link: '/zh/apps/stream-deck' },
          { text: 'Story Planner', link: '/zh/apps/story-planner' },
          { text: 'Surge', link: '/zh/apps/surge' },
          { text: 'TablePro', link: '/zh/apps/tablepro' },
          { text: 'Tadam', link: '/zh/apps/tadam' },
          { text: 'Tally', link: '/zh/apps/tally' },
          { text: 'Telegram', link: '/zh/apps/telegram' },
          { text: 'Tembo', link: '/zh/apps/tembo' },
          { text: 'Terminology', link: '/zh/apps/terminology' },
          { text: 'Termius', link: '/zh/apps/termius' },
          { text: 'Textastic', link: '/zh/apps/textastic' },
          { text: 'Textwell', link: '/zh/apps/textwell' },
          { text: 'TextMate', link: '/zh/apps/textmate' },
          { text: 'Theia', link: '/zh/apps/theia' },
          { text: 'Things', link: '/zh/apps/things' },
          { text: 'Thunder', link: '/zh/apps/thunder' },
          { text: 'Tim', link: '/zh/apps/tim' },
          { text: 'Timing', link: '/zh/apps/timing' },
          { text: 'Timer+', link: '/zh/apps/timer-plus' },
          { text: 'Timepage', link: '/zh/apps/timepage' },
          { text: 'Today Habit Tracker', link: '/zh/apps/today-habit-tracker' },
          { text: 'Todoist', link: '/zh/apps/todoist' },
          { text: 'Tower', link: '/zh/apps/tower' },
          { text: 'Trae', link: '/zh/apps/trae' },
          { text: 'Trae China', link: '/zh/apps/trae-cn' },
          { text: 'Trello', link: '/zh/apps/trello' },
          { text: 'Trust Wallet', link: '/zh/apps/trust-wallet' },
          { text: 'TrueContext', link: '/zh/apps/truecontext' },
          { text: 'Ulysses', link: '/zh/apps/ulysses' },
          { text: 'uPic', link: '/zh/apps/upic' },
          { text: 'UpNote', link: '/zh/apps/upnote' },
          { text: 'Verdent', link: '/zh/apps/verdent' },
          { text: 'Viber', link: '/zh/apps/viber' },
          { text: 'VS Code', link: '/zh/apps/vscode' },
          { text: 'VS Code Insiders', link: '/zh/apps/vscode-insiders' },
          { text: 'VSCodium', link: '/zh/apps/vscodium' },
          { text: 'Warp', link: '/zh/apps/warp' },
          { text: 'WaterMinder', link: '/zh/apps/waterminder' },
          { text: 'Waze', link: '/zh/apps/waze' },
          { text: 'Webex', link: '/zh/apps/webex' },
          { text: 'WebStorm', link: '/zh/apps/webstorm' },
          { text: 'WeMeet', link: '/zh/apps/wemeet' },
          { text: 'what3words', link: '/zh/apps/what3words' },
          { text: 'Where To', link: '/zh/apps/whereto' },
          { text: 'Windsurf', link: '/zh/apps/windsurf' },
          { text: 'Working Copy', link: '/zh/apps/working-copy' },
          { text: 'Written Down', link: '/zh/apps/written-down' },
          { text: 'Xcode', link: '/zh/apps/xcode' },
          { text: 'Yandex Maps', link: '/zh/apps/yandex-maps' },
          { text: 'Yandex Navigator', link: '/zh/apps/yandex-navigator' },
          { text: 'Yoink for iOS', link: '/zh/apps/yoink-ios' },
          { text: 'Zed', link: '/zh/apps/zed' },
          { text: 'Zoom', link: '/zh/apps/zoom' },
        ],
      },
      {
        text: '扩展',
        items: [{ text: '示例', link: '/zh/extra/examples' }],
      },
    ],

    search: { options: searchOptions() },
  },
})

function searchOptions(): Partial<DefaultTheme.AlgoliaSearchOptions> {
  return {
    placeholder: '搜索文档',
    translations: {
      button: {
        buttonText: '搜索文档',
        buttonAriaLabel: '搜索文档',
      },
      modal: {
        searchBox: {
          clearButtonTitle: '清除查询条件',
          clearButtonAriaLabel: '清除查询条件',
          closeButtonText: '关闭',
          closeButtonAriaLabel: '关闭',
          placeholderText: '搜索文档',
          placeholderTextAskAi: '向 AI 提问：',
          placeholderTextAskAiStreaming: '回答中...',
          searchInputLabel: '搜索',
          backToKeywordSearchButtonText: '返回关键字搜索',
          backToKeywordSearchButtonAriaLabel: '返回关键字搜索',
        },
        startScreen: {
          recentSearchesTitle: '搜索历史',
          noRecentSearchesText: '没有搜索历史',
          saveRecentSearchButtonTitle: '保存至搜索历史',
          removeRecentSearchButtonTitle: '从搜索历史中移除',
          favoriteSearchesTitle: '收藏',
          removeFavoriteSearchButtonTitle: '从收藏中移除',
          recentConversationsTitle: '最近的对话',
          removeRecentConversationButtonTitle: '从历史记录中删除对话',
        },
        errorScreen: {
          titleText: '无法获取结果',
          helpText: '你可能需要检查你的网络连接',
        },
        noResultsScreen: {
          noResultsText: '无法找到相关结果',
          suggestedQueryText: '你可以尝试查询',
          reportMissingResultsText: '你认为该查询应该有结果？',
          reportMissingResultsLinkText: '点击反馈',
        },
        resultsScreen: {
          askAiPlaceholder: '向 AI 提问： ',
        },
        askAiScreen: {
          disclaimerText: '答案由 AI 生成，可能不准确，请自行验证。',
          relatedSourcesText: '相关来源',
          thinkingText: '思考中...',
          copyButtonText: '复制',
          copyButtonCopiedText: '已复制！',
          copyButtonTitle: '复制',
          likeButtonTitle: '赞',
          dislikeButtonTitle: '踩',
          thanksForFeedbackText: '感谢你的反馈！',
          preToolCallText: '搜索中...',
          duringToolCallText: '搜索 ',
          afterToolCallText: '已搜索',
          // aggregatedToolCallText: '已搜索',
        },
        footer: {
          selectText: '选择',
          submitQuestionText: '提交问题',
          selectKeyAriaLabel: 'Enter 键',
          navigateText: '切换',
          navigateUpKeyAriaLabel: '向上箭头',
          navigateDownKeyAriaLabel: '向下箭头',
          closeText: '关闭',
          backToSearchText: '返回搜索',
          closeKeyAriaLabel: 'Esc 键',
          poweredByText: '搜索提供者',
        },
      },
    },
  }
}
